// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "TelemetryDataFile.proto" (package "IRacingTools.Models", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { FileInfo } from "./FileInfo";
import { TrackLayoutMetadata } from "./TrackLayoutMetadata";
/**
 * @generated from protobuf message IRacingTools.Models.TelemetryDataFile
 */
export interface TelemetryDataFile {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string alias = 2;
     */
    alias: string;
    /**
     * @generated from protobuf field: IRacingTools.Models.TelemetryDataFile.Status status = 3;
     */
    status: TelemetryDataFile_Status;
    /**
     * *
     * Track Layout ID
     *
     * @generated from protobuf field: IRacingTools.Models.TrackLayoutMetadata track_layout_metadata = 5;
     */
    trackLayoutMetadata?: TrackLayoutMetadata;
    /**
     * @generated from protobuf field: IRacingTools.Models.FileInfo file_info = 10;
     */
    fileInfo?: FileInfo;
    /**
     * @generated from protobuf field: string error_details = 20;
     */
    errorDetails: string;
}
/**
 * @generated from protobuf enum IRacingTools.Models.TelemetryDataFile.Status
 */
export enum TelemetryDataFile_Status {
    /**
     * @generated from protobuf enum value: STATUS_CREATED = 0;
     */
    CREATED = 0,
    /**
     * @generated from protobuf enum value: STATUS_AVAILABLE = 5;
     */
    AVAILABLE = 5,
    /**
     * @generated from protobuf enum value: STATUS_INVALID = 10;
     */
    INVALID = 10,
    /**
     * @generated from protobuf enum value: STATUS_ERROR = 20;
     */
    ERROR = 20
}
// @generated message type with reflection information, may provide speed optimized methods
class TelemetryDataFile$Type extends MessageType<TelemetryDataFile> {
    constructor() {
        super("IRacingTools.Models.TelemetryDataFile", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "alias", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "enum", T: () => ["IRacingTools.Models.TelemetryDataFile.Status", TelemetryDataFile_Status, "STATUS_"] },
            { no: 5, name: "track_layout_metadata", kind: "message", T: () => TrackLayoutMetadata },
            { no: 10, name: "file_info", kind: "message", T: () => FileInfo },
            { no: 20, name: "error_details", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TelemetryDataFile>): TelemetryDataFile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.alias = "";
        message.status = 0;
        message.errorDetails = "";
        if (value !== undefined)
            reflectionMergePartial<TelemetryDataFile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TelemetryDataFile): TelemetryDataFile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string alias */ 2:
                    message.alias = reader.string();
                    break;
                case /* IRacingTools.Models.TelemetryDataFile.Status status */ 3:
                    message.status = reader.int32();
                    break;
                case /* IRacingTools.Models.TrackLayoutMetadata track_layout_metadata */ 5:
                    message.trackLayoutMetadata = TrackLayoutMetadata.internalBinaryRead(reader, reader.uint32(), options, message.trackLayoutMetadata);
                    break;
                case /* IRacingTools.Models.FileInfo file_info */ 10:
                    message.fileInfo = FileInfo.internalBinaryRead(reader, reader.uint32(), options, message.fileInfo);
                    break;
                case /* string error_details */ 20:
                    message.errorDetails = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TelemetryDataFile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string alias = 2; */
        if (message.alias !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.alias);
        /* IRacingTools.Models.TelemetryDataFile.Status status = 3; */
        if (message.status !== 0)
            writer.tag(3, WireType.Varint).int32(message.status);
        /* IRacingTools.Models.TrackLayoutMetadata track_layout_metadata = 5; */
        if (message.trackLayoutMetadata)
            TrackLayoutMetadata.internalBinaryWrite(message.trackLayoutMetadata, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* IRacingTools.Models.FileInfo file_info = 10; */
        if (message.fileInfo)
            FileInfo.internalBinaryWrite(message.fileInfo, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* string error_details = 20; */
        if (message.errorDetails !== "")
            writer.tag(20, WireType.LengthDelimited).string(message.errorDetails);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.TelemetryDataFile
 */
export const TelemetryDataFile = new TelemetryDataFile$Type();
