// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "RPC/Messages/IPCDataServerMessages.proto" (package "IRacingTools.Models.RPC.DataServer", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Any } from "../../google/protobuf/any";
import { SessionEventType } from "../Events/SessionEvent";
import { SessionDataVarHeader } from "../../Session/SessionState";
/**
 * @generated from protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerClientMetadata
 */
export interface IPCDataServerClientMetadata {
    /**
     * @generated from protobuf field: uint32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: uint32 pid = 5;
     */
    pid: number;
}
/**
 * @generated from protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerSessionDataVarHeaders
 */
export interface IPCDataServerSessionDataVarHeaders {
    /**
     * @generated from protobuf field: repeated IRacingTools.Models.Session.SessionDataVarHeader headers = 1;
     */
    headers: SessionDataVarHeader[];
}
/**
 * @generated from protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerSetSubscriptions
 */
export interface IPCDataServerSetSubscriptions {
    /**
     * @generated from protobuf field: repeated IRacingTools.Models.RPC.Events.SessionEventType event_types = 1;
     */
    eventTypes: SessionEventType[];
    /**
     * @generated from protobuf field: repeated string data_var_header_names = 10;
     */
    dataVarHeaderNames: string[];
}
/**
 * @generated from protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerError
 */
export interface IPCDataServerError {
    /**
     * @generated from protobuf field: string code = 1;
     */
    code: string;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
    /**
     * @generated from protobuf field: string stack_trace = 3;
     */
    stackTrace: string;
}
/**
 * @generated from protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerMessage
 */
export interface IPCDataServerMessage {
    /**
     * @generated from protobuf field: IRacingTools.Models.RPC.DataServer.IPCDataServerMessage.Type type = 1;
     */
    type: IPCDataServerMessage_Type;
    /**
     * @generated from protobuf field: optional IRacingTools.Models.RPC.Events.SessionEventType event_type = 2;
     */
    eventType?: SessionEventType;
    /**
     * @generated from protobuf field: bool is_error = 8;
     */
    isError: boolean;
    /**
     * @generated from protobuf field: optional IRacingTools.Models.RPC.DataServer.IPCDataServerError error = 9;
     */
    error?: IPCDataServerError;
    /**
     * @generated from protobuf field: google.protobuf.Any payload = 10;
     */
    payload?: Any;
}
/**
 * @generated from protobuf enum IRacingTools.Models.RPC.DataServer.IPCDataServerMessage.Type
 */
export enum IPCDataServerMessage_Type {
    /**
     * @generated from protobuf enum value: TYPE_EVENT = 0;
     */
    EVENT = 0,
    /**
     * @generated from protobuf enum value: TYPE_SET_CLIENT_METADATA = 1;
     */
    SET_CLIENT_METADATA = 1,
    /**
     * @generated from protobuf enum value: TYPE_GET_SESSION_METADATA = 3;
     */
    GET_SESSION_METADATA = 3,
    /**
     * @generated from protobuf enum value: TYPE_GET_SESSION_DATA_HEADERS = 4;
     */
    GET_SESSION_DATA_HEADERS = 4,
    /**
     * @generated from protobuf enum value: TYPE_SET_SUBSCRIPTIONS = 5;
     */
    SET_SUBSCRIPTIONS = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class IPCDataServerClientMetadata$Type extends MessageType<IPCDataServerClientMetadata> {
    constructor() {
        super("IRacingTools.Models.RPC.DataServer.IPCDataServerClientMetadata", [
            { no: 1, name: "id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "pid", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<IPCDataServerClientMetadata>): IPCDataServerClientMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.pid = 0;
        if (value !== undefined)
            reflectionMergePartial<IPCDataServerClientMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IPCDataServerClientMetadata): IPCDataServerClientMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 id */ 1:
                    message.id = reader.uint32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* uint32 pid */ 5:
                    message.pid = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IPCDataServerClientMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).uint32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* uint32 pid = 5; */
        if (message.pid !== 0)
            writer.tag(5, WireType.Varint).uint32(message.pid);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerClientMetadata
 */
export const IPCDataServerClientMetadata = new IPCDataServerClientMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IPCDataServerSessionDataVarHeaders$Type extends MessageType<IPCDataServerSessionDataVarHeaders> {
    constructor() {
        super("IRacingTools.Models.RPC.DataServer.IPCDataServerSessionDataVarHeaders", [
            { no: 1, name: "headers", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => SessionDataVarHeader }
        ]);
    }
    create(value?: PartialMessage<IPCDataServerSessionDataVarHeaders>): IPCDataServerSessionDataVarHeaders {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.headers = [];
        if (value !== undefined)
            reflectionMergePartial<IPCDataServerSessionDataVarHeaders>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IPCDataServerSessionDataVarHeaders): IPCDataServerSessionDataVarHeaders {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated IRacingTools.Models.Session.SessionDataVarHeader headers */ 1:
                    message.headers.push(SessionDataVarHeader.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IPCDataServerSessionDataVarHeaders, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated IRacingTools.Models.Session.SessionDataVarHeader headers = 1; */
        for (let i = 0; i < message.headers.length; i++)
            SessionDataVarHeader.internalBinaryWrite(message.headers[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerSessionDataVarHeaders
 */
export const IPCDataServerSessionDataVarHeaders = new IPCDataServerSessionDataVarHeaders$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IPCDataServerSetSubscriptions$Type extends MessageType<IPCDataServerSetSubscriptions> {
    constructor() {
        super("IRacingTools.Models.RPC.DataServer.IPCDataServerSetSubscriptions", [
            { no: 1, name: "event_types", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["IRacingTools.Models.RPC.Events.SessionEventType", SessionEventType, "SESSION_EVENT_TYPE_"] },
            { no: 10, name: "data_var_header_names", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<IPCDataServerSetSubscriptions>): IPCDataServerSetSubscriptions {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventTypes = [];
        message.dataVarHeaderNames = [];
        if (value !== undefined)
            reflectionMergePartial<IPCDataServerSetSubscriptions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IPCDataServerSetSubscriptions): IPCDataServerSetSubscriptions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated IRacingTools.Models.RPC.Events.SessionEventType event_types */ 1:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.eventTypes.push(reader.int32());
                    else
                        message.eventTypes.push(reader.int32());
                    break;
                case /* repeated string data_var_header_names */ 10:
                    message.dataVarHeaderNames.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IPCDataServerSetSubscriptions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated IRacingTools.Models.RPC.Events.SessionEventType event_types = 1; */
        if (message.eventTypes.length) {
            writer.tag(1, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.eventTypes.length; i++)
                writer.int32(message.eventTypes[i]);
            writer.join();
        }
        /* repeated string data_var_header_names = 10; */
        for (let i = 0; i < message.dataVarHeaderNames.length; i++)
            writer.tag(10, WireType.LengthDelimited).string(message.dataVarHeaderNames[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerSetSubscriptions
 */
export const IPCDataServerSetSubscriptions = new IPCDataServerSetSubscriptions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IPCDataServerError$Type extends MessageType<IPCDataServerError> {
    constructor() {
        super("IRacingTools.Models.RPC.DataServer.IPCDataServerError", [
            { no: 1, name: "code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "stack_trace", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<IPCDataServerError>): IPCDataServerError {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.code = "";
        message.message = "";
        message.stackTrace = "";
        if (value !== undefined)
            reflectionMergePartial<IPCDataServerError>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IPCDataServerError): IPCDataServerError {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string code */ 1:
                    message.code = reader.string();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* string stack_trace */ 3:
                    message.stackTrace = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IPCDataServerError, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string code = 1; */
        if (message.code !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.code);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* string stack_trace = 3; */
        if (message.stackTrace !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.stackTrace);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerError
 */
export const IPCDataServerError = new IPCDataServerError$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IPCDataServerMessage$Type extends MessageType<IPCDataServerMessage> {
    constructor() {
        super("IRacingTools.Models.RPC.DataServer.IPCDataServerMessage", [
            { no: 1, name: "type", kind: "enum", T: () => ["IRacingTools.Models.RPC.DataServer.IPCDataServerMessage.Type", IPCDataServerMessage_Type, "TYPE_"] },
            { no: 2, name: "event_type", kind: "enum", opt: true, T: () => ["IRacingTools.Models.RPC.Events.SessionEventType", SessionEventType, "SESSION_EVENT_TYPE_"] },
            { no: 8, name: "is_error", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "error", kind: "message", T: () => IPCDataServerError },
            { no: 10, name: "payload", kind: "message", T: () => Any }
        ]);
    }
    create(value?: PartialMessage<IPCDataServerMessage>): IPCDataServerMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.isError = false;
        if (value !== undefined)
            reflectionMergePartial<IPCDataServerMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IPCDataServerMessage): IPCDataServerMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* IRacingTools.Models.RPC.DataServer.IPCDataServerMessage.Type type */ 1:
                    message.type = reader.int32();
                    break;
                case /* optional IRacingTools.Models.RPC.Events.SessionEventType event_type */ 2:
                    message.eventType = reader.int32();
                    break;
                case /* bool is_error */ 8:
                    message.isError = reader.bool();
                    break;
                case /* optional IRacingTools.Models.RPC.DataServer.IPCDataServerError error */ 9:
                    message.error = IPCDataServerError.internalBinaryRead(reader, reader.uint32(), options, message.error);
                    break;
                case /* google.protobuf.Any payload */ 10:
                    message.payload = Any.internalBinaryRead(reader, reader.uint32(), options, message.payload);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IPCDataServerMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* IRacingTools.Models.RPC.DataServer.IPCDataServerMessage.Type type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* optional IRacingTools.Models.RPC.Events.SessionEventType event_type = 2; */
        if (message.eventType !== undefined)
            writer.tag(2, WireType.Varint).int32(message.eventType);
        /* bool is_error = 8; */
        if (message.isError !== false)
            writer.tag(8, WireType.Varint).bool(message.isError);
        /* optional IRacingTools.Models.RPC.DataServer.IPCDataServerError error = 9; */
        if (message.error)
            IPCDataServerError.internalBinaryWrite(message.error, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Any payload = 10; */
        if (message.payload)
            Any.internalBinaryWrite(message.payload, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerMessage
 */
export const IPCDataServerMessage = new IPCDataServerMessage$Type();
