// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "RPC/Messages/IPCDataServerMessages.proto" (package "IRacingTools.Models.RPC.DataServer", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Any } from "../../google/protobuf/any";
/**
 * @generated from protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerClientMetadata
 */
export interface IPCDataServerClientMetadata {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: uint32 pid = 5;
     */
    pid: number;
    /**
     * @generated from protobuf field: uint32 connection_id = 10;
     */
    connectionId: number;
}
/**
 * @generated from protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerState
 */
export interface IPCDataServerState {
    /**
     * @generated from protobuf field: bool session_connected = 1;
     */
    sessionConnected: boolean;
    /**
     * @generated from protobuf field: int32 session_id = 2;
     */
    sessionId: number;
    /**
     * @generated from protobuf field: uint32 pid = 3;
     */
    pid: number;
    /**
     * @generated from protobuf field: string name = 5;
     */
    name: string;
    /**
     * @generated from protobuf field: map<string, IRacingTools.Models.RPC.DataServer.IPCDataServerClientMetadata> clients = 10;
     */
    clients: {
        [key: string]: IPCDataServerClientMetadata;
    };
}
/**
 * @generated from protobuf message IRacingTools.Models.RPC.DataServer.PongMessage
 */
export interface PongMessage {
    /**
     * @generated from protobuf field: uint32 ping_count = 1;
     */
    pingCount: number;
}
/**
 * @generated from protobuf message IRacingTools.Models.RPC.DataServer.ListMessage
 */
export interface ListMessage {
    /**
     * TARGET TO BE QUERIED; THIS CAN BE ANYTHING I.E. `dashboards`, `overlays`, ETC
     *  AS LONG AS YOUR ROUTE KNOWS WHAT TO LOOK FOR, ANY VALUE WORKS
     *
     * @generated from protobuf field: string subject = 1;
     */
    subject: string;
    /**
     * POTENTIALLY A FILTERING QUERY
     *
     * @generated from protobuf field: string query = 2;
     */
    query: string;
    // ARGUMENTS FOR QUERY
    // map<string, string> parameters = 5;

    /**
     * RESULT OR REQUEST
     *
     * @generated from protobuf field: bool is_result = 10;
     */
    isResult: boolean;
    /**
     * @generated from protobuf field: int32 results_page = 11;
     */
    resultsPage: number;
    /**
     * IF `results_per_page == -1` ALL RESULTS SHOULD BE RETURNED
     *
     * @generated from protobuf field: int32 results_per_page = 12;
     */
    resultsPerPage: number;
    /**
     * @generated from protobuf field: uint32 results_count = 13;
     */
    resultsCount: number;
    /**
     * `ANY[]` WITH RESULTS TO BE UNPACKED
     *
     * @generated from protobuf field: repeated google.protobuf.Any results = 20;
     */
    results: Any[];
    /**
     * ANY ERROR
     *
     * @generated from protobuf field: string error_details = 60;
     */
    errorDetails: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class IPCDataServerClientMetadata$Type extends MessageType<IPCDataServerClientMetadata> {
    constructor() {
        super("IRacingTools.Models.RPC.DataServer.IPCDataServerClientMetadata", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "pid", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "connection_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<IPCDataServerClientMetadata>): IPCDataServerClientMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.pid = 0;
        message.connectionId = 0;
        if (value !== undefined)
            reflectionMergePartial<IPCDataServerClientMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IPCDataServerClientMetadata): IPCDataServerClientMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* uint32 pid */ 5:
                    message.pid = reader.uint32();
                    break;
                case /* uint32 connection_id */ 10:
                    message.connectionId = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IPCDataServerClientMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* uint32 pid = 5; */
        if (message.pid !== 0)
            writer.tag(5, WireType.Varint).uint32(message.pid);
        /* uint32 connection_id = 10; */
        if (message.connectionId !== 0)
            writer.tag(10, WireType.Varint).uint32(message.connectionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerClientMetadata
 */
export const IPCDataServerClientMetadata = new IPCDataServerClientMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IPCDataServerState$Type extends MessageType<IPCDataServerState> {
    constructor() {
        super("IRacingTools.Models.RPC.DataServer.IPCDataServerState", [
            { no: 1, name: "session_connected", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "session_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "pid", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "clients", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "message", T: () => IPCDataServerClientMetadata } }
        ]);
    }
    create(value?: PartialMessage<IPCDataServerState>): IPCDataServerState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessionConnected = false;
        message.sessionId = 0;
        message.pid = 0;
        message.name = "";
        message.clients = {};
        if (value !== undefined)
            reflectionMergePartial<IPCDataServerState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IPCDataServerState): IPCDataServerState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool session_connected */ 1:
                    message.sessionConnected = reader.bool();
                    break;
                case /* int32 session_id */ 2:
                    message.sessionId = reader.int32();
                    break;
                case /* uint32 pid */ 3:
                    message.pid = reader.uint32();
                    break;
                case /* string name */ 5:
                    message.name = reader.string();
                    break;
                case /* map<string, IRacingTools.Models.RPC.DataServer.IPCDataServerClientMetadata> clients */ 10:
                    this.binaryReadMap10(message.clients, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap10(map: IPCDataServerState["clients"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof IPCDataServerState["clients"] | undefined, val: IPCDataServerState["clients"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = IPCDataServerClientMetadata.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for field IRacingTools.Models.RPC.DataServer.IPCDataServerState.clients");
            }
        }
        map[key ?? ""] = val ?? IPCDataServerClientMetadata.create();
    }
    internalBinaryWrite(message: IPCDataServerState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool session_connected = 1; */
        if (message.sessionConnected !== false)
            writer.tag(1, WireType.Varint).bool(message.sessionConnected);
        /* int32 session_id = 2; */
        if (message.sessionId !== 0)
            writer.tag(2, WireType.Varint).int32(message.sessionId);
        /* uint32 pid = 3; */
        if (message.pid !== 0)
            writer.tag(3, WireType.Varint).uint32(message.pid);
        /* string name = 5; */
        if (message.name !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.name);
        /* map<string, IRacingTools.Models.RPC.DataServer.IPCDataServerClientMetadata> clients = 10; */
        for (let k of globalThis.Object.keys(message.clients)) {
            writer.tag(10, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
            IPCDataServerClientMetadata.internalBinaryWrite(message.clients[k], writer, options);
            writer.join().join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.RPC.DataServer.IPCDataServerState
 */
export const IPCDataServerState = new IPCDataServerState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PongMessage$Type extends MessageType<PongMessage> {
    constructor() {
        super("IRacingTools.Models.RPC.DataServer.PongMessage", [
            { no: 1, name: "ping_count", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<PongMessage>): PongMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pingCount = 0;
        if (value !== undefined)
            reflectionMergePartial<PongMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PongMessage): PongMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 ping_count */ 1:
                    message.pingCount = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PongMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 ping_count = 1; */
        if (message.pingCount !== 0)
            writer.tag(1, WireType.Varint).uint32(message.pingCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.RPC.DataServer.PongMessage
 */
export const PongMessage = new PongMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListMessage$Type extends MessageType<ListMessage> {
    constructor() {
        super("IRacingTools.Models.RPC.DataServer.ListMessage", [
            { no: 1, name: "subject", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "is_result", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 11, name: "results_page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "results_per_page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "results_count", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 20, name: "results", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Any },
            { no: 60, name: "error_details", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListMessage>): ListMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.subject = "";
        message.query = "";
        message.isResult = false;
        message.resultsPage = 0;
        message.resultsPerPage = 0;
        message.resultsCount = 0;
        message.results = [];
        message.errorDetails = "";
        if (value !== undefined)
            reflectionMergePartial<ListMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListMessage): ListMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string subject */ 1:
                    message.subject = reader.string();
                    break;
                case /* string query */ 2:
                    message.query = reader.string();
                    break;
                case /* bool is_result */ 10:
                    message.isResult = reader.bool();
                    break;
                case /* int32 results_page */ 11:
                    message.resultsPage = reader.int32();
                    break;
                case /* int32 results_per_page */ 12:
                    message.resultsPerPage = reader.int32();
                    break;
                case /* uint32 results_count */ 13:
                    message.resultsCount = reader.uint32();
                    break;
                case /* repeated google.protobuf.Any results */ 20:
                    message.results.push(Any.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string error_details */ 60:
                    message.errorDetails = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string subject = 1; */
        if (message.subject !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.subject);
        /* string query = 2; */
        if (message.query !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.query);
        /* bool is_result = 10; */
        if (message.isResult !== false)
            writer.tag(10, WireType.Varint).bool(message.isResult);
        /* int32 results_page = 11; */
        if (message.resultsPage !== 0)
            writer.tag(11, WireType.Varint).int32(message.resultsPage);
        /* int32 results_per_page = 12; */
        if (message.resultsPerPage !== 0)
            writer.tag(12, WireType.Varint).int32(message.resultsPerPage);
        /* uint32 results_count = 13; */
        if (message.resultsCount !== 0)
            writer.tag(13, WireType.Varint).uint32(message.resultsCount);
        /* repeated google.protobuf.Any results = 20; */
        for (let i = 0; i < message.results.length; i++)
            Any.internalBinaryWrite(message.results[i], writer.tag(20, WireType.LengthDelimited).fork(), options).join();
        /* string error_details = 60; */
        if (message.errorDetails !== "")
            writer.tag(60, WireType.LengthDelimited).string(message.errorDetails);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.RPC.DataServer.ListMessage
 */
export const ListMessage = new ListMessage$Type();
