// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "RPC/Events/SessionEvent.proto" (package "VRKit.Models.RPC.Events", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { SessionDataFrame } from "../../Session/SessionState";
import { SessionType } from "../../Session/SessionState";
import { SessionMetadata } from "../../Session/SessionState";
/**
 * @generated from protobuf message VRKit.Models.RPC.Events.SessionChangedEvent
 */
export interface SessionChangedEvent {
    /**
     * @generated from protobuf field: bool is_available = 1;
     */
    isAvailable: boolean;
    /**
     * @generated from protobuf field: optional uint32 session_id = 2;
     */
    sessionId?: number;
    /**
     * @generated from protobuf field: optional VRKit.Models.Session.SessionMetadata session_metadata = 10;
     */
    sessionMetadata?: SessionMetadata;
}
/**
 * @generated from protobuf message VRKit.Models.RPC.Events.SessionEventData
 */
export interface SessionEventData {
    /**
     * @generated from protobuf field: VRKit.Models.RPC.Events.SessionEventType type = 1;
     */
    type: SessionEventType;
    /**
     * @generated from protobuf field: string session_id = 10;
     */
    sessionId: string;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionType session_type = 11;
     */
    sessionType: SessionType;
    /**
     * @generated from protobuf oneof: payload
     */
    payload: {
        oneofKind: "sessionChangedEvent";
        /**
         * @generated from protobuf field: VRKit.Models.RPC.Events.SessionChangedEvent session_changed_event = 50;
         */
        sessionChangedEvent: SessionChangedEvent;
    } | {
        oneofKind: "sessionMetadata";
        /**
         * @generated from protobuf field: VRKit.Models.Session.SessionMetadata session_metadata = 52;
         */
        sessionMetadata: SessionMetadata;
    } | {
        oneofKind: "sessionDataFrame";
        /**
         * @generated from protobuf field: VRKit.Models.Session.SessionDataFrame session_data_frame = 53;
         */
        sessionDataFrame: SessionDataFrame;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf enum VRKit.Models.RPC.Events.SessionEventType
 */
export enum SessionEventType {
    /**
     * @generated from protobuf enum value: SESSION_EVENT_TYPE_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: SESSION_EVENT_TYPE_SESSION_CHANGED = 1;
     */
    SESSION_CHANGED = 1,
    /**
     * @generated from protobuf enum value: SESSION_EVENT_TYPE_METADATA_CHANGED = 2;
     */
    METADATA_CHANGED = 2,
    /**
     * @generated from protobuf enum value: SESSION_EVENT_TYPE_DATA_FRAME = 3;
     */
    DATA_FRAME = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class SessionChangedEvent$Type extends MessageType<SessionChangedEvent> {
    constructor() {
        super("VRKit.Models.RPC.Events.SessionChangedEvent", [
            { no: 1, name: "is_available", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "session_id", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "session_metadata", kind: "message", T: () => SessionMetadata }
        ]);
    }
    create(value?: PartialMessage<SessionChangedEvent>): SessionChangedEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isAvailable = false;
        if (value !== undefined)
            reflectionMergePartial<SessionChangedEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionChangedEvent): SessionChangedEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_available */ 1:
                    message.isAvailable = reader.bool();
                    break;
                case /* optional uint32 session_id */ 2:
                    message.sessionId = reader.uint32();
                    break;
                case /* optional VRKit.Models.Session.SessionMetadata session_metadata */ 10:
                    message.sessionMetadata = SessionMetadata.internalBinaryRead(reader, reader.uint32(), options, message.sessionMetadata);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionChangedEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_available = 1; */
        if (message.isAvailable !== false)
            writer.tag(1, WireType.Varint).bool(message.isAvailable);
        /* optional uint32 session_id = 2; */
        if (message.sessionId !== undefined)
            writer.tag(2, WireType.Varint).uint32(message.sessionId);
        /* optional VRKit.Models.Session.SessionMetadata session_metadata = 10; */
        if (message.sessionMetadata)
            SessionMetadata.internalBinaryWrite(message.sessionMetadata, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message VRKit.Models.RPC.Events.SessionChangedEvent
 */
export const SessionChangedEvent = new SessionChangedEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SessionEventData$Type extends MessageType<SessionEventData> {
    constructor() {
        super("VRKit.Models.RPC.Events.SessionEventData", [
            { no: 1, name: "type", kind: "enum", T: () => ["VRKit.Models.RPC.Events.SessionEventType", SessionEventType, "SESSION_EVENT_TYPE_"] },
            { no: 10, name: "session_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "session_type", kind: "enum", T: () => ["VRKit.Models.Session.SessionType", SessionType, "SESSION_TYPE_"] },
            { no: 50, name: "session_changed_event", kind: "message", oneof: "payload", T: () => SessionChangedEvent },
            { no: 52, name: "session_metadata", kind: "message", oneof: "payload", T: () => SessionMetadata },
            { no: 53, name: "session_data_frame", kind: "message", oneof: "payload", T: () => SessionDataFrame }
        ]);
    }
    create(value?: PartialMessage<SessionEventData>): SessionEventData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.sessionId = "";
        message.sessionType = 0;
        message.payload = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<SessionEventData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionEventData): SessionEventData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* VRKit.Models.RPC.Events.SessionEventType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* string session_id */ 10:
                    message.sessionId = reader.string();
                    break;
                case /* VRKit.Models.Session.SessionType session_type */ 11:
                    message.sessionType = reader.int32();
                    break;
                case /* VRKit.Models.RPC.Events.SessionChangedEvent session_changed_event */ 50:
                    message.payload = {
                        oneofKind: "sessionChangedEvent",
                        sessionChangedEvent: SessionChangedEvent.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).sessionChangedEvent)
                    };
                    break;
                case /* VRKit.Models.Session.SessionMetadata session_metadata */ 52:
                    message.payload = {
                        oneofKind: "sessionMetadata",
                        sessionMetadata: SessionMetadata.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).sessionMetadata)
                    };
                    break;
                case /* VRKit.Models.Session.SessionDataFrame session_data_frame */ 53:
                    message.payload = {
                        oneofKind: "sessionDataFrame",
                        sessionDataFrame: SessionDataFrame.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).sessionDataFrame)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionEventData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* VRKit.Models.RPC.Events.SessionEventType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* string session_id = 10; */
        if (message.sessionId !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.sessionId);
        /* VRKit.Models.Session.SessionType session_type = 11; */
        if (message.sessionType !== 0)
            writer.tag(11, WireType.Varint).int32(message.sessionType);
        /* VRKit.Models.RPC.Events.SessionChangedEvent session_changed_event = 50; */
        if (message.payload.oneofKind === "sessionChangedEvent")
            SessionChangedEvent.internalBinaryWrite(message.payload.sessionChangedEvent, writer.tag(50, WireType.LengthDelimited).fork(), options).join();
        /* VRKit.Models.Session.SessionMetadata session_metadata = 52; */
        if (message.payload.oneofKind === "sessionMetadata")
            SessionMetadata.internalBinaryWrite(message.payload.sessionMetadata, writer.tag(52, WireType.LengthDelimited).fork(), options).join();
        /* VRKit.Models.Session.SessionDataFrame session_data_frame = 53; */
        if (message.payload.oneofKind === "sessionDataFrame")
            SessionDataFrame.internalBinaryWrite(message.payload.sessionDataFrame, writer.tag(53, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message VRKit.Models.RPC.Events.SessionEventData
 */
export const SessionEventData = new SessionEventData$Type();
