name: NodeJS Setup & Deps Action

description: "NodeJS Setup & Deps Action"

inputs:
  NPM_TOKEN:
    description: "NPM_TOKEN"
    required: true
  FONT_AWESOME_TOKEN:
    description: "FONT_AWESOME_TOKEN"
    required: true
#  example_input:
#    description: "An example input for the action"
#    required: true
#    default: "Default Value"

outputs: {}
#  example_output:
#    description: "An example output"

runs:
  using: composite
  steps:
    - name: "Configure NPM/YARN"
      shell: pwsh
      run: |
        echo "network-timeout 240000" >> ~/.yarnrc
        echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}" >> ~/.npmrc
        echo "script-shell=C:\\Program Files\\git\\bin\\bash.exe" >> ~/.npmrc
        echo "@mui:registry=https://registry.npmjs.org/" >> ~/.npmrc
        echo "@awesome.me:registry=https://npm.fontawesome.com/" >> ~/.npmrc
        echo "@fortawesome:registry=https://npm.fontawesome.com/" >> ~/.npmrc
        echo "//npm.fontawesome.com/:_authToken=${{ inputs.FONT_AWESOME_TOKEN }}" >> ~/.npmrc

        echo "network-timeout 240000" > .yarnrc
        echo "registry=https://registry.npmjs.org/" > .npmrc
        echo "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}" >> .npmrc
        echo "script-shell=C:\\Program Files\\git\\bin\\bash.exe" >> .npmrc
        echo "@mui:registry=https://registry.npmjs.org/" >> .npmrc
        echo "@awesome.me:registry=https://npm.fontawesome.com/" >> .npmrc
        echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
        echo "//npm.fontawesome.com/:_authToken=${{ inputs.FONT_AWESOME_TOKEN }}" >> .npmrc

    - name: Use Node v22
      uses: actions/setup-node@v4
      with:
      node-version: '22'
      cache: "yarn"
      cache-dependency-path: '**/yarn.lock'

    - name: "Node Install Deps"
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        yarn install --frozen-lockfile --immutable



#    - name: Do Something
#      run: echo "Input provided: ${{ inputs.example_input }}"

#    - name: Set Output
#      run: echo "example_output=Success" >> $GITHUB_ENV