// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "AppInterfaceTypes.proto" (package "IRacingTools.Models", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum IRacingTools.Models.SupportedGame
 */
export enum SupportedGame {
    /**
     * @generated from protobuf enum value: SUPPORTED_GAME_IRACING = 0;
     */
    IRACING = 0
}
