// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "AppSettings.proto" (package "IRacingTools.Models", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message IRacingTools.Models.AppSettings
 */
export interface AppSettings {
    /**
     * @generated from protobuf field: string activeDashboardId = 1;
     */
    activeDashboardId: string;
    /**
     * @generated from protobuf field: bool autoconnect = 5;
     */
    autoconnect: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class AppSettings$Type extends MessageType<AppSettings> {
    constructor() {
        super("IRacingTools.Models.AppSettings", [
            { no: 1, name: "activeDashboardId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "autoconnect", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<AppSettings>): AppSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.activeDashboardId = "";
        message.autoconnect = false;
        if (value !== undefined)
            reflectionMergePartial<AppSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AppSettings): AppSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string activeDashboardId */ 1:
                    message.activeDashboardId = reader.string();
                    break;
                case /* bool autoconnect */ 5:
                    message.autoconnect = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AppSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string activeDashboardId = 1; */
        if (message.activeDashboardId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.activeDashboardId);
        /* bool autoconnect = 5; */
        if (message.autoconnect !== false)
            writer.tag(5, WireType.Varint).bool(message.autoconnect);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.AppSettings
 */
export const AppSettings = new AppSettings$Type();
