// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "OverlayTypes.proto" (package "IRacingTools.Models.Dashboard", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { VRLayout } from "./Geometry";
import { RectI } from "./Geometry";
/**
 * @generated from protobuf message IRacingTools.Models.Dashboard.OverlayBaseSettings
 */
export interface OverlayBaseSettings {
    /**
     * @generated from protobuf field: int32 fps = 1;
     */
    fps: number;
}
/**
 * @generated from protobuf message IRacingTools.Models.Dashboard.OverlayInfo
 */
export interface OverlayInfo {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: IRacingTools.Models.Dashboard.OverlayKind kind = 2;
     */
    kind: OverlayKind;
    /**
     * @generated from protobuf field: string component_id = 3;
     */
    componentId: string;
    /**
     * @generated from protobuf field: string name = 5;
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 6;
     */
    description: string;
    /**
     * @generated from protobuf field: repeated string data_var_names = 20;
     */
    dataVarNames: string[];
    /**
     * @generated from protobuf field: IRacingTools.Models.Dashboard.OverlayBaseSettings settings = 30;
     */
    settings?: OverlayBaseSettings;
}
/**
 * @generated from protobuf message IRacingTools.Models.Dashboard.OverlayPlacement
 */
export interface OverlayPlacement {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string overlay_id = 5;
     */
    overlayId: string;
    /**
     * @generated from protobuf field: IRacingTools.Models.RectI screen_rect = 10;
     */
    screenRect?: RectI;
    /**
     * @generated from protobuf field: IRacingTools.Models.VRLayout vr_layout = 21;
     */
    vrLayout?: VRLayout;
}
/**
 * @generated from protobuf message IRacingTools.Models.Dashboard.OverlayConfig
 */
export interface OverlayConfig {
    /**
     * @generated from protobuf field: IRacingTools.Models.Dashboard.OverlayInfo overlay = 1;
     */
    overlay?: OverlayInfo;
    /**
     * @generated from protobuf field: IRacingTools.Models.Dashboard.OverlayPlacement placement = 2;
     */
    placement?: OverlayPlacement;
    /**
     * @generated from protobuf field: bool is_screen = 10;
     */
    isScreen: boolean;
}
/**
 * @generated from protobuf enum IRacingTools.Models.Dashboard.OverlayAnchor
 */
export enum OverlayAnchor {
    /**
     * @generated from protobuf enum value: OVERLAY_ANCHOR_CENTER = 0;
     */
    CENTER = 0,
    /**
     * @generated from protobuf enum value: OVERLAY_ANCHOR_TOP_LEFT = 1;
     */
    TOP_LEFT = 1,
    /**
     * @generated from protobuf enum value: OVERLAY_ANCHOR_TOP_RIGHT = 2;
     */
    TOP_RIGHT = 2,
    /**
     * @generated from protobuf enum value: OVERLAY_ANCHOR_BOTTOM_RIGHT = 3;
     */
    BOTTOM_RIGHT = 3,
    /**
     * @generated from protobuf enum value: OVERLAY_ANCHOR_BOTTOM_LEFT = 4;
     */
    BOTTOM_LEFT = 4
}
/**
 * @generated from protobuf enum IRacingTools.Models.Dashboard.OverlayKind
 */
export enum OverlayKind {
    /**
     *  OVERLAY_KIND_TRACK_MAP = 0;
     *  OVERLAY_KIND_CLOCK = 1;
     *
     * @generated from protobuf enum value: OVERLAY_KIND_PLUGIN = 0;
     */
    PLUGIN = 0,
    /**
     * @generated from protobuf enum value: OVERLAY_KIND_EDITOR_INFO = 99;
     */
    EDITOR_INFO = 99
}
// @generated message type with reflection information, may provide speed optimized methods
class OverlayBaseSettings$Type extends MessageType<OverlayBaseSettings> {
    constructor() {
        super("IRacingTools.Models.Dashboard.OverlayBaseSettings", [
            { no: 1, name: "fps", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<OverlayBaseSettings>): OverlayBaseSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fps = 0;
        if (value !== undefined)
            reflectionMergePartial<OverlayBaseSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OverlayBaseSettings): OverlayBaseSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 fps */ 1:
                    message.fps = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OverlayBaseSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 fps = 1; */
        if (message.fps !== 0)
            writer.tag(1, WireType.Varint).int32(message.fps);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.Dashboard.OverlayBaseSettings
 */
export const OverlayBaseSettings = new OverlayBaseSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OverlayInfo$Type extends MessageType<OverlayInfo> {
    constructor() {
        super("IRacingTools.Models.Dashboard.OverlayInfo", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "kind", kind: "enum", T: () => ["IRacingTools.Models.Dashboard.OverlayKind", OverlayKind, "OVERLAY_KIND_"] },
            { no: 3, name: "component_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "data_var_names", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 30, name: "settings", kind: "message", T: () => OverlayBaseSettings }
        ]);
    }
    create(value?: PartialMessage<OverlayInfo>): OverlayInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.kind = 0;
        message.componentId = "";
        message.name = "";
        message.description = "";
        message.dataVarNames = [];
        if (value !== undefined)
            reflectionMergePartial<OverlayInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OverlayInfo): OverlayInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* IRacingTools.Models.Dashboard.OverlayKind kind */ 2:
                    message.kind = reader.int32();
                    break;
                case /* string component_id */ 3:
                    message.componentId = reader.string();
                    break;
                case /* string name */ 5:
                    message.name = reader.string();
                    break;
                case /* string description */ 6:
                    message.description = reader.string();
                    break;
                case /* repeated string data_var_names */ 20:
                    message.dataVarNames.push(reader.string());
                    break;
                case /* IRacingTools.Models.Dashboard.OverlayBaseSettings settings */ 30:
                    message.settings = OverlayBaseSettings.internalBinaryRead(reader, reader.uint32(), options, message.settings);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OverlayInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* IRacingTools.Models.Dashboard.OverlayKind kind = 2; */
        if (message.kind !== 0)
            writer.tag(2, WireType.Varint).int32(message.kind);
        /* string component_id = 3; */
        if (message.componentId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.componentId);
        /* string name = 5; */
        if (message.name !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.name);
        /* string description = 6; */
        if (message.description !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.description);
        /* repeated string data_var_names = 20; */
        for (let i = 0; i < message.dataVarNames.length; i++)
            writer.tag(20, WireType.LengthDelimited).string(message.dataVarNames[i]);
        /* IRacingTools.Models.Dashboard.OverlayBaseSettings settings = 30; */
        if (message.settings)
            OverlayBaseSettings.internalBinaryWrite(message.settings, writer.tag(30, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.Dashboard.OverlayInfo
 */
export const OverlayInfo = new OverlayInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OverlayPlacement$Type extends MessageType<OverlayPlacement> {
    constructor() {
        super("IRacingTools.Models.Dashboard.OverlayPlacement", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "overlay_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "screen_rect", kind: "message", T: () => RectI },
            { no: 21, name: "vr_layout", kind: "message", T: () => VRLayout }
        ]);
    }
    create(value?: PartialMessage<OverlayPlacement>): OverlayPlacement {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.overlayId = "";
        if (value !== undefined)
            reflectionMergePartial<OverlayPlacement>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OverlayPlacement): OverlayPlacement {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string overlay_id */ 5:
                    message.overlayId = reader.string();
                    break;
                case /* IRacingTools.Models.RectI screen_rect */ 10:
                    message.screenRect = RectI.internalBinaryRead(reader, reader.uint32(), options, message.screenRect);
                    break;
                case /* IRacingTools.Models.VRLayout vr_layout */ 21:
                    message.vrLayout = VRLayout.internalBinaryRead(reader, reader.uint32(), options, message.vrLayout);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OverlayPlacement, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string overlay_id = 5; */
        if (message.overlayId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.overlayId);
        /* IRacingTools.Models.RectI screen_rect = 10; */
        if (message.screenRect)
            RectI.internalBinaryWrite(message.screenRect, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* IRacingTools.Models.VRLayout vr_layout = 21; */
        if (message.vrLayout)
            VRLayout.internalBinaryWrite(message.vrLayout, writer.tag(21, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.Dashboard.OverlayPlacement
 */
export const OverlayPlacement = new OverlayPlacement$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OverlayConfig$Type extends MessageType<OverlayConfig> {
    constructor() {
        super("IRacingTools.Models.Dashboard.OverlayConfig", [
            { no: 1, name: "overlay", kind: "message", T: () => OverlayInfo },
            { no: 2, name: "placement", kind: "message", T: () => OverlayPlacement },
            { no: 10, name: "is_screen", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<OverlayConfig>): OverlayConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isScreen = false;
        if (value !== undefined)
            reflectionMergePartial<OverlayConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OverlayConfig): OverlayConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* IRacingTools.Models.Dashboard.OverlayInfo overlay */ 1:
                    message.overlay = OverlayInfo.internalBinaryRead(reader, reader.uint32(), options, message.overlay);
                    break;
                case /* IRacingTools.Models.Dashboard.OverlayPlacement placement */ 2:
                    message.placement = OverlayPlacement.internalBinaryRead(reader, reader.uint32(), options, message.placement);
                    break;
                case /* bool is_screen */ 10:
                    message.isScreen = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OverlayConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* IRacingTools.Models.Dashboard.OverlayInfo overlay = 1; */
        if (message.overlay)
            OverlayInfo.internalBinaryWrite(message.overlay, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* IRacingTools.Models.Dashboard.OverlayPlacement placement = 2; */
        if (message.placement)
            OverlayPlacement.internalBinaryWrite(message.placement, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bool is_screen = 10; */
        if (message.isScreen !== false)
            writer.tag(10, WireType.Varint).bool(message.isScreen);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IRacingTools.Models.Dashboard.OverlayConfig
 */
export const OverlayConfig = new OverlayConfig$Type();
