// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "TrackTypes.proto" (package "VRKit.Models", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum VRKit.Models.TrackType
 */
export enum TrackType {
    /**
     * @generated from protobuf enum value: TRACK_TYPE_ROAD = 0;
     */
    ROAD = 0,
    /**
     * @generated from protobuf enum value: TRACK_TYPE_OVAL = 1;
     */
    OVAL = 1,
    /**
     * @generated from protobuf enum value: TRACK_TYPE_DIRT = 2;
     */
    DIRT = 2,
    /**
     * @generated from protobuf enum value: TRACK_TYPE_DIRT_OVAL = 3;
     */
    DIRT_OVAL = 3
}
