// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "Session/SessionState.proto" (package "VRKit.Models.Session", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { FileInfo } from "../FileInfo";
import { TrackLayoutMetadata } from "../TrackLayoutMetadata";
/**
 * @generated from protobuf message VRKit.Models.Session.SessionTiming
 */
export interface SessionTiming {
    /**
     * @generated from protobuf field: bool is_live = 1;
     */
    isLive: boolean;
    /**
     * @generated from protobuf field: bool is_valid = 2;
     */
    isValid: boolean;
    /**
     * @generated from protobuf field: int32 sample_index = 50;
     */
    sampleIndex: number;
    /**
     * @generated from protobuf field: int32 sample_count = 51;
     */
    sampleCount: number;
    /**
     * @generated from protobuf field: int32 ticks = 60;
     */
    ticks: number;
    /**
     * @generated from protobuf field: int32 tick_count = 61;
     */
    tickCount: number;
    /**
     * @generated from protobuf field: int32 session_sub_count = 70;
     */
    sessionSubCount: number;
    /**
     * @generated from protobuf field: int32 session_sub_num = 71;
     */
    sessionSubNum: number;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionSubType session_sub_type = 72;
     */
    sessionSubType: SessionSubType;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionSubTimingType session_sub_timing_type = 73;
     */
    sessionSubTimingType: SessionSubTimingType;
    /**
     * @generated from protobuf field: int32 session_sub_lap = 75;
     */
    sessionSubLap: number;
    /**
     * @generated from protobuf field: int32 session_sub_lap_remaining = 76;
     */
    sessionSubLapRemaining: number;
    /**
     * @generated from protobuf field: int32 session_sub_lap_count = 77;
     */
    sessionSubLapCount: number;
    /**
     * @generated from protobuf field: int32 session_sub_time = 80;
     */
    sessionSubTime: number;
    /**
     * @generated from protobuf field: int32 session_sub_time_remaining = 81;
     */
    sessionSubTimeRemaining: number;
    /**
     * @generated from protobuf field: int32 session_sub_time_total = 82;
     */
    sessionSubTimeTotal: number;
}
/**
 * @generated from protobuf message VRKit.Models.Session.SessionMetadata
 */
export interface SessionMetadata {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: int32 session_id = 2;
     */
    sessionId: number;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionType type = 3;
     */
    type: SessionType;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionStatus status = 5;
     */
    status: SessionStatus;
    /**
     * @generated from protobuf field: int32 sub_count = 6;
     */
    subCount: number;
    /**
     * @generated from protobuf field: int32 sub_id = 7;
     */
    subId: number;
    /**
     * @generated from protobuf field: int32 sub_num = 8;
     */
    subNum: number;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionSubType sub_type = 9;
     */
    subType: SessionSubType;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionTiming timing = 15;
     */
    timing?: SessionTiming;
    /**
     * @generated from protobuf field: VRKit.Models.TrackLayoutMetadata track_layout_metadata = 20;
     */
    trackLayoutMetadata?: TrackLayoutMetadata;
    /**
     * @generated from protobuf field: VRKit.Models.FileInfo file_info = 21;
     */
    fileInfo?: FileInfo;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionCarStatus car_status = 30;
     */
    carStatus: SessionCarStatus;
    /**
     * @generated from protobuf field: optional VRKit.Models.Session.SessionPlaybackState playback_state = 31;
     */
    playbackState?: SessionPlaybackState;
    /**
     * @generated from protobuf field: optional string session_info_json = 90;
     */
    sessionInfoJson?: string;
    /**
     * @generated from protobuf field: optional string session_info_yaml = 91;
     */
    sessionInfoYaml?: string;
}
/**
 * @generated from protobuf message VRKit.Models.Session.SessionDataVarHeader
 */
export interface SessionDataVarHeader {
    /**
     * @generated from protobuf field: int32 index = 1;
     */
    index: number;
    /**
     * @generated from protobuf field: int32 count = 2;
     */
    count: number;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionDataVarType type = 3;
     */
    type: SessionDataVarType;
    /**
     * @generated from protobuf field: string name = 5;
     */
    name: string;
}
/**
 * @generated from protobuf message VRKit.Models.Session.SessionDataFrame
 */
export interface SessionDataFrame {
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionTiming timing = 1;
     */
    timing?: SessionTiming;
    /**
     * @generated from protobuf field: map<int32, VRKit.Models.Session.SessionDataFrame.VarValues> data_values = 10;
     */
    dataValues: {
        [key: number]: SessionDataFrame_VarValues;
    };
}
/**
 * @generated from protobuf message VRKit.Models.Session.SessionDataFrame.Value
 */
export interface SessionDataFrame_Value {
    /**
     * @generated from protobuf oneof: data
     */
    data: {
        oneofKind: "charValue";
        /**
         * @generated from protobuf field: uint32 char_value = 1;
         */
        charValue: number;
    } | {
        oneofKind: "boolValue";
        /**
         * @generated from protobuf field: bool bool_value = 2;
         */
        boolValue: boolean;
    } | {
        oneofKind: "int32Value";
        /**
         * @generated from protobuf field: int32 int32_value = 3;
         */
        int32Value: number;
    } | {
        oneofKind: "bitmaskValue";
        /**
         * @generated from protobuf field: uint32 bitmask_value = 4;
         */
        bitmaskValue: number;
    } | {
        oneofKind: "floatValue";
        /**
         * @generated from protobuf field: float float_value = 5;
         */
        floatValue: number;
    } | {
        oneofKind: "doubleValue";
        /**
         * @generated from protobuf field: double double_value = 6;
         */
        doubleValue: number;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message VRKit.Models.Session.SessionDataFrame.VarValues
 */
export interface SessionDataFrame_VarValues {
    /**
     * @generated from protobuf field: int32 index = 1;
     */
    index: number;
    /**
     * @generated from protobuf field: int32 count = 2;
     */
    count: number;
    /**
     * @generated from protobuf field: VRKit.Models.Session.SessionDataVarType type = 3;
     */
    type: SessionDataVarType;
    /**
     * @generated from protobuf field: repeated VRKit.Models.Session.SessionDataFrame.Value slot = 5;
     */
    slot: SessionDataFrame_Value[];
}
/**
 * @generated from protobuf enum VRKit.Models.Session.SessionPlaybackState
 */
export enum SessionPlaybackState {
    /**
     * @generated from protobuf enum value: SESSION_PLAYBACK_STATE_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: SESSION_PLAYBACK_STATE_PLAYING = 1;
     */
    PLAYING = 1,
    /**
     * @generated from protobuf enum value: SESSION_PLAYBACK_STATE_PAUSED = 2;
     */
    PAUSED = 2,
    /**
     * @generated from protobuf enum value: SESSION_PLAYBACK_STATE_STOPPED = 3;
     */
    STOPPED = 3
}
/**
 * Enum representing the sub-types of a session. This distinguishes
 * specific parts of a session, such as practice, qualifying, or race phases.
 *
 * @generated from protobuf enum VRKit.Models.Session.SessionSubType
 */
export enum SessionSubType {
    /**
     * @generated from protobuf enum value: SESSION_SUB_TYPE_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: SESSION_SUB_TYPE_PRACTICE = 1;
     */
    PRACTICE = 1,
    /**
     * @generated from protobuf enum value: SESSION_SUB_TYPE_QUALIFY = 2;
     */
    QUALIFY = 2,
    /**
     * @generated from protobuf enum value: SESSION_SUB_TYPE_RACE = 3;
     */
    RACE = 3
}
/**
 * @generated from protobuf enum VRKit.Models.Session.SessionSubTimingType
 */
export enum SessionSubTimingType {
    /**
     * @generated from protobuf enum value: SESSION_SUB_TIMING_TYPE_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: SESSION_SUB_TIMING_TYPE_TIMED = 1;
     */
    TIMED = 1,
    /**
     * @generated from protobuf enum value: SESSION_SUB_TIMING_TYPE_LAPS = 2;
     */
    LAPS = 2
}
/**
 * @generated from protobuf enum VRKit.Models.Session.SessionType
 */
export enum SessionType {
    /**
     * @generated from protobuf enum value: SESSION_TYPE_LIVE = 0;
     */
    LIVE = 0,
    /**
     * @generated from protobuf enum value: SESSION_TYPE_DISK = 1;
     */
    DISK = 1
}
/**
 * @generated from protobuf enum VRKit.Models.Session.SessionCarStatus
 */
export enum SessionCarStatus {
    /**
     * @generated from protobuf enum value: SESSION_CAR_STATUS_INVALID = 0;
     */
    INVALID = 0,
    /**
     * @generated from protobuf enum value: SESSION_CAR_STATUS_GET_IN_CAR = 1;
     */
    GET_IN_CAR = 1,
    /**
     * @generated from protobuf enum value: SESSION_CAR_STATUS_WARMUP = 3;
     */
    WARMUP = 3,
    /**
     * @generated from protobuf enum value: SESSION_CAR_STATUS_PARADE_LAPS = 4;
     */
    PARADE_LAPS = 4,
    /**
     * @generated from protobuf enum value: SESSION_CAR_STATUS_RACE = 5;
     */
    RACE = 5,
    /**
     * @generated from protobuf enum value: SESSION_CAR_STATUS_CHECKERED = 6;
     */
    CHECKERED = 6,
    /**
     * @generated from protobuf enum value: SESSION_CAR_STATUS_COOLDOWN = 7;
     */
    COOLDOWN = 7
}
/**
 * @generated from protobuf enum VRKit.Models.Session.SessionStatus
 */
export enum SessionStatus {
    /**
     * @generated from protobuf enum value: SESSION_STATUS_CREATED = 0;
     */
    CREATED = 0,
    /**
     * @generated from protobuf enum value: SESSION_STATUS_READY = 1;
     */
    READY = 1,
    /**
     * @generated from protobuf enum value: SESSION_STATUS_PAUSED = 2;
     */
    PAUSED = 2,
    /**
     * @generated from protobuf enum value: SESSION_STATUS_RUNNING = 5;
     */
    RUNNING = 5,
    /**
     * @generated from protobuf enum value: SESSION_STATUS_ERROR = 10;
     */
    ERROR = 10
}
/**
 * @generated from protobuf enum VRKit.Models.Session.SessionDataVarType
 */
export enum SessionDataVarType {
    /**
     * @generated from protobuf enum value: SESSION_DATA_VAR_TYPE_CHAR = 0;
     */
    CHAR = 0,
    /**
     * @generated from protobuf enum value: SESSION_DATA_VAR_TYPE_BOOL = 1;
     */
    BOOL = 1,
    /**
     * @generated from protobuf enum value: SESSION_DATA_VAR_TYPE_INT32 = 2;
     */
    INT32 = 2,
    /**
     * @generated from protobuf enum value: SESSION_DATA_VAR_TYPE_BITMASK = 3;
     */
    BITMASK = 3,
    /**
     * @generated from protobuf enum value: SESSION_DATA_VAR_TYPE_FLOAT = 4;
     */
    FLOAT = 4,
    /**
     * @generated from protobuf enum value: SESSION_DATA_VAR_TYPE_DOUBLE = 5;
     */
    DOUBLE = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class SessionTiming$Type extends MessageType<SessionTiming> {
    constructor() {
        super("VRKit.Models.Session.SessionTiming", [
            { no: 1, name: "is_live", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "is_valid", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 50, name: "sample_index", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 51, name: "sample_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 60, name: "ticks", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 61, name: "tick_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 70, name: "session_sub_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 71, name: "session_sub_num", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 72, name: "session_sub_type", kind: "enum", T: () => ["VRKit.Models.Session.SessionSubType", SessionSubType, "SESSION_SUB_TYPE_"] },
            { no: 73, name: "session_sub_timing_type", kind: "enum", T: () => ["VRKit.Models.Session.SessionSubTimingType", SessionSubTimingType, "SESSION_SUB_TIMING_TYPE_"] },
            { no: 75, name: "session_sub_lap", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 76, name: "session_sub_lap_remaining", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 77, name: "session_sub_lap_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 80, name: "session_sub_time", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 81, name: "session_sub_time_remaining", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 82, name: "session_sub_time_total", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SessionTiming>): SessionTiming {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isLive = false;
        message.isValid = false;
        message.sampleIndex = 0;
        message.sampleCount = 0;
        message.ticks = 0;
        message.tickCount = 0;
        message.sessionSubCount = 0;
        message.sessionSubNum = 0;
        message.sessionSubType = 0;
        message.sessionSubTimingType = 0;
        message.sessionSubLap = 0;
        message.sessionSubLapRemaining = 0;
        message.sessionSubLapCount = 0;
        message.sessionSubTime = 0;
        message.sessionSubTimeRemaining = 0;
        message.sessionSubTimeTotal = 0;
        if (value !== undefined)
            reflectionMergePartial<SessionTiming>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionTiming): SessionTiming {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_live */ 1:
                    message.isLive = reader.bool();
                    break;
                case /* bool is_valid */ 2:
                    message.isValid = reader.bool();
                    break;
                case /* int32 sample_index */ 50:
                    message.sampleIndex = reader.int32();
                    break;
                case /* int32 sample_count */ 51:
                    message.sampleCount = reader.int32();
                    break;
                case /* int32 ticks */ 60:
                    message.ticks = reader.int32();
                    break;
                case /* int32 tick_count */ 61:
                    message.tickCount = reader.int32();
                    break;
                case /* int32 session_sub_count */ 70:
                    message.sessionSubCount = reader.int32();
                    break;
                case /* int32 session_sub_num */ 71:
                    message.sessionSubNum = reader.int32();
                    break;
                case /* VRKit.Models.Session.SessionSubType session_sub_type */ 72:
                    message.sessionSubType = reader.int32();
                    break;
                case /* VRKit.Models.Session.SessionSubTimingType session_sub_timing_type */ 73:
                    message.sessionSubTimingType = reader.int32();
                    break;
                case /* int32 session_sub_lap */ 75:
                    message.sessionSubLap = reader.int32();
                    break;
                case /* int32 session_sub_lap_remaining */ 76:
                    message.sessionSubLapRemaining = reader.int32();
                    break;
                case /* int32 session_sub_lap_count */ 77:
                    message.sessionSubLapCount = reader.int32();
                    break;
                case /* int32 session_sub_time */ 80:
                    message.sessionSubTime = reader.int32();
                    break;
                case /* int32 session_sub_time_remaining */ 81:
                    message.sessionSubTimeRemaining = reader.int32();
                    break;
                case /* int32 session_sub_time_total */ 82:
                    message.sessionSubTimeTotal = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionTiming, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_live = 1; */
        if (message.isLive !== false)
            writer.tag(1, WireType.Varint).bool(message.isLive);
        /* bool is_valid = 2; */
        if (message.isValid !== false)
            writer.tag(2, WireType.Varint).bool(message.isValid);
        /* int32 sample_index = 50; */
        if (message.sampleIndex !== 0)
            writer.tag(50, WireType.Varint).int32(message.sampleIndex);
        /* int32 sample_count = 51; */
        if (message.sampleCount !== 0)
            writer.tag(51, WireType.Varint).int32(message.sampleCount);
        /* int32 ticks = 60; */
        if (message.ticks !== 0)
            writer.tag(60, WireType.Varint).int32(message.ticks);
        /* int32 tick_count = 61; */
        if (message.tickCount !== 0)
            writer.tag(61, WireType.Varint).int32(message.tickCount);
        /* int32 session_sub_count = 70; */
        if (message.sessionSubCount !== 0)
            writer.tag(70, WireType.Varint).int32(message.sessionSubCount);
        /* int32 session_sub_num = 71; */
        if (message.sessionSubNum !== 0)
            writer.tag(71, WireType.Varint).int32(message.sessionSubNum);
        /* VRKit.Models.Session.SessionSubType session_sub_type = 72; */
        if (message.sessionSubType !== 0)
            writer.tag(72, WireType.Varint).int32(message.sessionSubType);
        /* VRKit.Models.Session.SessionSubTimingType session_sub_timing_type = 73; */
        if (message.sessionSubTimingType !== 0)
            writer.tag(73, WireType.Varint).int32(message.sessionSubTimingType);
        /* int32 session_sub_lap = 75; */
        if (message.sessionSubLap !== 0)
            writer.tag(75, WireType.Varint).int32(message.sessionSubLap);
        /* int32 session_sub_lap_remaining = 76; */
        if (message.sessionSubLapRemaining !== 0)
            writer.tag(76, WireType.Varint).int32(message.sessionSubLapRemaining);
        /* int32 session_sub_lap_count = 77; */
        if (message.sessionSubLapCount !== 0)
            writer.tag(77, WireType.Varint).int32(message.sessionSubLapCount);
        /* int32 session_sub_time = 80; */
        if (message.sessionSubTime !== 0)
            writer.tag(80, WireType.Varint).int32(message.sessionSubTime);
        /* int32 session_sub_time_remaining = 81; */
        if (message.sessionSubTimeRemaining !== 0)
            writer.tag(81, WireType.Varint).int32(message.sessionSubTimeRemaining);
        /* int32 session_sub_time_total = 82; */
        if (message.sessionSubTimeTotal !== 0)
            writer.tag(82, WireType.Varint).int32(message.sessionSubTimeTotal);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message VRKit.Models.Session.SessionTiming
 */
export const SessionTiming = new SessionTiming$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SessionMetadata$Type extends MessageType<SessionMetadata> {
    constructor() {
        super("VRKit.Models.Session.SessionMetadata", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "session_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["VRKit.Models.Session.SessionType", SessionType, "SESSION_TYPE_"] },
            { no: 5, name: "status", kind: "enum", T: () => ["VRKit.Models.Session.SessionStatus", SessionStatus, "SESSION_STATUS_"] },
            { no: 6, name: "sub_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "sub_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "sub_num", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "sub_type", kind: "enum", T: () => ["VRKit.Models.Session.SessionSubType", SessionSubType, "SESSION_SUB_TYPE_"] },
            { no: 15, name: "timing", kind: "message", T: () => SessionTiming },
            { no: 20, name: "track_layout_metadata", kind: "message", T: () => TrackLayoutMetadata },
            { no: 21, name: "file_info", kind: "message", T: () => FileInfo },
            { no: 30, name: "car_status", kind: "enum", T: () => ["VRKit.Models.Session.SessionCarStatus", SessionCarStatus, "SESSION_CAR_STATUS_"] },
            { no: 31, name: "playback_state", kind: "enum", opt: true, T: () => ["VRKit.Models.Session.SessionPlaybackState", SessionPlaybackState, "SESSION_PLAYBACK_STATE_"] },
            { no: 90, name: "session_info_json", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 91, name: "session_info_yaml", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SessionMetadata>): SessionMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.sessionId = 0;
        message.type = 0;
        message.status = 0;
        message.subCount = 0;
        message.subId = 0;
        message.subNum = 0;
        message.subType = 0;
        message.carStatus = 0;
        if (value !== undefined)
            reflectionMergePartial<SessionMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionMetadata): SessionMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* int32 session_id */ 2:
                    message.sessionId = reader.int32();
                    break;
                case /* VRKit.Models.Session.SessionType type */ 3:
                    message.type = reader.int32();
                    break;
                case /* VRKit.Models.Session.SessionStatus status */ 5:
                    message.status = reader.int32();
                    break;
                case /* int32 sub_count */ 6:
                    message.subCount = reader.int32();
                    break;
                case /* int32 sub_id */ 7:
                    message.subId = reader.int32();
                    break;
                case /* int32 sub_num */ 8:
                    message.subNum = reader.int32();
                    break;
                case /* VRKit.Models.Session.SessionSubType sub_type */ 9:
                    message.subType = reader.int32();
                    break;
                case /* VRKit.Models.Session.SessionTiming timing */ 15:
                    message.timing = SessionTiming.internalBinaryRead(reader, reader.uint32(), options, message.timing);
                    break;
                case /* VRKit.Models.TrackLayoutMetadata track_layout_metadata */ 20:
                    message.trackLayoutMetadata = TrackLayoutMetadata.internalBinaryRead(reader, reader.uint32(), options, message.trackLayoutMetadata);
                    break;
                case /* VRKit.Models.FileInfo file_info */ 21:
                    message.fileInfo = FileInfo.internalBinaryRead(reader, reader.uint32(), options, message.fileInfo);
                    break;
                case /* VRKit.Models.Session.SessionCarStatus car_status */ 30:
                    message.carStatus = reader.int32();
                    break;
                case /* optional VRKit.Models.Session.SessionPlaybackState playback_state */ 31:
                    message.playbackState = reader.int32();
                    break;
                case /* optional string session_info_json */ 90:
                    message.sessionInfoJson = reader.string();
                    break;
                case /* optional string session_info_yaml */ 91:
                    message.sessionInfoYaml = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* int32 session_id = 2; */
        if (message.sessionId !== 0)
            writer.tag(2, WireType.Varint).int32(message.sessionId);
        /* VRKit.Models.Session.SessionType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* VRKit.Models.Session.SessionStatus status = 5; */
        if (message.status !== 0)
            writer.tag(5, WireType.Varint).int32(message.status);
        /* int32 sub_count = 6; */
        if (message.subCount !== 0)
            writer.tag(6, WireType.Varint).int32(message.subCount);
        /* int32 sub_id = 7; */
        if (message.subId !== 0)
            writer.tag(7, WireType.Varint).int32(message.subId);
        /* int32 sub_num = 8; */
        if (message.subNum !== 0)
            writer.tag(8, WireType.Varint).int32(message.subNum);
        /* VRKit.Models.Session.SessionSubType sub_type = 9; */
        if (message.subType !== 0)
            writer.tag(9, WireType.Varint).int32(message.subType);
        /* VRKit.Models.Session.SessionTiming timing = 15; */
        if (message.timing)
            SessionTiming.internalBinaryWrite(message.timing, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        /* VRKit.Models.TrackLayoutMetadata track_layout_metadata = 20; */
        if (message.trackLayoutMetadata)
            TrackLayoutMetadata.internalBinaryWrite(message.trackLayoutMetadata, writer.tag(20, WireType.LengthDelimited).fork(), options).join();
        /* VRKit.Models.FileInfo file_info = 21; */
        if (message.fileInfo)
            FileInfo.internalBinaryWrite(message.fileInfo, writer.tag(21, WireType.LengthDelimited).fork(), options).join();
        /* VRKit.Models.Session.SessionCarStatus car_status = 30; */
        if (message.carStatus !== 0)
            writer.tag(30, WireType.Varint).int32(message.carStatus);
        /* optional VRKit.Models.Session.SessionPlaybackState playback_state = 31; */
        if (message.playbackState !== undefined)
            writer.tag(31, WireType.Varint).int32(message.playbackState);
        /* optional string session_info_json = 90; */
        if (message.sessionInfoJson !== undefined)
            writer.tag(90, WireType.LengthDelimited).string(message.sessionInfoJson);
        /* optional string session_info_yaml = 91; */
        if (message.sessionInfoYaml !== undefined)
            writer.tag(91, WireType.LengthDelimited).string(message.sessionInfoYaml);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message VRKit.Models.Session.SessionMetadata
 */
export const SessionMetadata = new SessionMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SessionDataVarHeader$Type extends MessageType<SessionDataVarHeader> {
    constructor() {
        super("VRKit.Models.Session.SessionDataVarHeader", [
            { no: 1, name: "index", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["VRKit.Models.Session.SessionDataVarType", SessionDataVarType, "SESSION_DATA_VAR_TYPE_"] },
            { no: 5, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SessionDataVarHeader>): SessionDataVarHeader {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.index = 0;
        message.count = 0;
        message.type = 0;
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<SessionDataVarHeader>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionDataVarHeader): SessionDataVarHeader {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 index */ 1:
                    message.index = reader.int32();
                    break;
                case /* int32 count */ 2:
                    message.count = reader.int32();
                    break;
                case /* VRKit.Models.Session.SessionDataVarType type */ 3:
                    message.type = reader.int32();
                    break;
                case /* string name */ 5:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionDataVarHeader, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 index = 1; */
        if (message.index !== 0)
            writer.tag(1, WireType.Varint).int32(message.index);
        /* int32 count = 2; */
        if (message.count !== 0)
            writer.tag(2, WireType.Varint).int32(message.count);
        /* VRKit.Models.Session.SessionDataVarType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* string name = 5; */
        if (message.name !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message VRKit.Models.Session.SessionDataVarHeader
 */
export const SessionDataVarHeader = new SessionDataVarHeader$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SessionDataFrame$Type extends MessageType<SessionDataFrame> {
    constructor() {
        super("VRKit.Models.Session.SessionDataFrame", [
            { no: 1, name: "timing", kind: "message", T: () => SessionTiming },
            { no: 10, name: "data_values", kind: "map", K: 5 /*ScalarType.INT32*/, V: { kind: "message", T: () => SessionDataFrame_VarValues } }
        ]);
    }
    create(value?: PartialMessage<SessionDataFrame>): SessionDataFrame {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.dataValues = {};
        if (value !== undefined)
            reflectionMergePartial<SessionDataFrame>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionDataFrame): SessionDataFrame {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* VRKit.Models.Session.SessionTiming timing */ 1:
                    message.timing = SessionTiming.internalBinaryRead(reader, reader.uint32(), options, message.timing);
                    break;
                case /* map<int32, VRKit.Models.Session.SessionDataFrame.VarValues> data_values */ 10:
                    this.binaryReadMap10(message.dataValues, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap10(map: SessionDataFrame["dataValues"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof SessionDataFrame["dataValues"] | undefined, val: SessionDataFrame["dataValues"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.int32();
                    break;
                case 2:
                    val = SessionDataFrame_VarValues.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for field VRKit.Models.Session.SessionDataFrame.data_values");
            }
        }
        map[key ?? 0] = val ?? SessionDataFrame_VarValues.create();
    }
    internalBinaryWrite(message: SessionDataFrame, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* VRKit.Models.Session.SessionTiming timing = 1; */
        if (message.timing)
            SessionTiming.internalBinaryWrite(message.timing, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* map<int32, VRKit.Models.Session.SessionDataFrame.VarValues> data_values = 10; */
        for (let k of globalThis.Object.keys(message.dataValues)) {
            writer.tag(10, WireType.LengthDelimited).fork().tag(1, WireType.Varint).int32(parseInt(k));
            writer.tag(2, WireType.LengthDelimited).fork();
            SessionDataFrame_VarValues.internalBinaryWrite(message.dataValues[k as any], writer, options);
            writer.join().join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message VRKit.Models.Session.SessionDataFrame
 */
export const SessionDataFrame = new SessionDataFrame$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SessionDataFrame_Value$Type extends MessageType<SessionDataFrame_Value> {
    constructor() {
        super("VRKit.Models.Session.SessionDataFrame.Value", [
            { no: 1, name: "char_value", kind: "scalar", oneof: "data", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "bool_value", kind: "scalar", oneof: "data", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "int32_value", kind: "scalar", oneof: "data", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "bitmask_value", kind: "scalar", oneof: "data", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "float_value", kind: "scalar", oneof: "data", T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "double_value", kind: "scalar", oneof: "data", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<SessionDataFrame_Value>): SessionDataFrame_Value {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<SessionDataFrame_Value>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionDataFrame_Value): SessionDataFrame_Value {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 char_value */ 1:
                    message.data = {
                        oneofKind: "charValue",
                        charValue: reader.uint32()
                    };
                    break;
                case /* bool bool_value */ 2:
                    message.data = {
                        oneofKind: "boolValue",
                        boolValue: reader.bool()
                    };
                    break;
                case /* int32 int32_value */ 3:
                    message.data = {
                        oneofKind: "int32Value",
                        int32Value: reader.int32()
                    };
                    break;
                case /* uint32 bitmask_value */ 4:
                    message.data = {
                        oneofKind: "bitmaskValue",
                        bitmaskValue: reader.uint32()
                    };
                    break;
                case /* float float_value */ 5:
                    message.data = {
                        oneofKind: "floatValue",
                        floatValue: reader.float()
                    };
                    break;
                case /* double double_value */ 6:
                    message.data = {
                        oneofKind: "doubleValue",
                        doubleValue: reader.double()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionDataFrame_Value, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 char_value = 1; */
        if (message.data.oneofKind === "charValue")
            writer.tag(1, WireType.Varint).uint32(message.data.charValue);
        /* bool bool_value = 2; */
        if (message.data.oneofKind === "boolValue")
            writer.tag(2, WireType.Varint).bool(message.data.boolValue);
        /* int32 int32_value = 3; */
        if (message.data.oneofKind === "int32Value")
            writer.tag(3, WireType.Varint).int32(message.data.int32Value);
        /* uint32 bitmask_value = 4; */
        if (message.data.oneofKind === "bitmaskValue")
            writer.tag(4, WireType.Varint).uint32(message.data.bitmaskValue);
        /* float float_value = 5; */
        if (message.data.oneofKind === "floatValue")
            writer.tag(5, WireType.Bit32).float(message.data.floatValue);
        /* double double_value = 6; */
        if (message.data.oneofKind === "doubleValue")
            writer.tag(6, WireType.Bit64).double(message.data.doubleValue);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message VRKit.Models.Session.SessionDataFrame.Value
 */
export const SessionDataFrame_Value = new SessionDataFrame_Value$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SessionDataFrame_VarValues$Type extends MessageType<SessionDataFrame_VarValues> {
    constructor() {
        super("VRKit.Models.Session.SessionDataFrame.VarValues", [
            { no: 1, name: "index", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["VRKit.Models.Session.SessionDataVarType", SessionDataVarType, "SESSION_DATA_VAR_TYPE_"] },
            { no: 5, name: "slot", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => SessionDataFrame_Value }
        ]);
    }
    create(value?: PartialMessage<SessionDataFrame_VarValues>): SessionDataFrame_VarValues {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.index = 0;
        message.count = 0;
        message.type = 0;
        message.slot = [];
        if (value !== undefined)
            reflectionMergePartial<SessionDataFrame_VarValues>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SessionDataFrame_VarValues): SessionDataFrame_VarValues {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 index */ 1:
                    message.index = reader.int32();
                    break;
                case /* int32 count */ 2:
                    message.count = reader.int32();
                    break;
                case /* VRKit.Models.Session.SessionDataVarType type */ 3:
                    message.type = reader.int32();
                    break;
                case /* repeated VRKit.Models.Session.SessionDataFrame.Value slot */ 5:
                    message.slot.push(SessionDataFrame_Value.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SessionDataFrame_VarValues, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 index = 1; */
        if (message.index !== 0)
            writer.tag(1, WireType.Varint).int32(message.index);
        /* int32 count = 2; */
        if (message.count !== 0)
            writer.tag(2, WireType.Varint).int32(message.count);
        /* VRKit.Models.Session.SessionDataVarType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* repeated VRKit.Models.Session.SessionDataFrame.Value slot = 5; */
        for (let i = 0; i < message.slot.length; i++)
            SessionDataFrame_Value.internalBinaryWrite(message.slot[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message VRKit.Models.Session.SessionDataFrame.VarValues
 */
export const SessionDataFrame_VarValues = new SessionDataFrame_VarValues$Type();
