"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LapMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAP_FIELD_NUMBER: builtins.int
    LAP_TIME_FIELD_NUMBER: builtins.int
    INCIDENT_COUNT_FIELD_NUMBER: builtins.int
    VALID_FIELD_NUMBER: builtins.int
    lap: builtins.int
    lap_time: builtins.int
    incident_count: builtins.int
    valid: builtins.bool
    def __init__(
        self,
        *,
        lap: builtins.int = ...,
        lap_time: builtins.int = ...,
        incident_count: builtins.int = ...,
        valid: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["incident_count", b"incident_count", "lap", b"lap", "lap_time", b"lap_time", "valid", b"valid"]) -> None: ...

global___LapMetadata = LapMetadata

@typing.final
class LapTrajectory(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    TRACK_ID_FIELD_NUMBER: builtins.int
    TRACK_NAME_FIELD_NUMBER: builtins.int
    TRACK_LAYOUT_NAME_FIELD_NUMBER: builtins.int
    TRACK_LAYOUT_ID_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    track_id: builtins.int
    track_name: builtins.str
    track_layout_name: builtins.str
    track_layout_id: builtins.str
    @property
    def metadata(self) -> global___LapMetadata: ...
    @property
    def path(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LapCoordinate]: ...
    def __init__(
        self,
        *,
        metadata: global___LapMetadata | None = ...,
        timestamp: builtins.int = ...,
        track_id: builtins.int = ...,
        track_name: builtins.str = ...,
        track_layout_name: builtins.str = ...,
        track_layout_id: builtins.str = ...,
        path: collections.abc.Iterable[global___LapCoordinate] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "path", b"path", "timestamp", b"timestamp", "track_id", b"track_id", "track_layout_id", b"track_layout_id", "track_layout_name", b"track_layout_name", "track_name", b"track_name"]) -> None: ...

global___LapTrajectory = LapTrajectory

@typing.final
class LapCoordinate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAP_TIME_FIELD_NUMBER: builtins.int
    LAP_PERCENT_COMPLETE_FIELD_NUMBER: builtins.int
    LAP_DISTANCE_FIELD_NUMBER: builtins.int
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    ALTITUDE_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    lap_time: builtins.int
    lap_percent_complete: builtins.float
    lap_distance: builtins.float
    latitude: builtins.float
    longitude: builtins.float
    altitude: builtins.float
    speed: builtins.float
    def __init__(
        self,
        *,
        lap_time: builtins.int = ...,
        lap_percent_complete: builtins.float = ...,
        lap_distance: builtins.float = ...,
        latitude: builtins.float = ...,
        longitude: builtins.float = ...,
        altitude: builtins.float = ...,
        speed: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["altitude", b"altitude", "lap_distance", b"lap_distance", "lap_percent_complete", b"lap_percent_complete", "lap_time", b"lap_time", "latitude", b"latitude", "longitude", b"longitude", "speed", b"speed"]) -> None: ...

global___LapCoordinate = LapCoordinate
