# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LapTrajectory.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LapCoordinate_pb2 as LapCoordinate__pb2
import TrackLayoutMetadata_pb2 as TrackLayoutMetadata__pb2
import FileInfo_pb2 as FileInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13LapTrajectory.proto\x12\x13IRacingTools.Models\x1a\x13LapCoordinate.proto\x1a\x19TrackLayoutMetadata.proto\x1a\x0e\x46ileInfo.proto\"\xe0\x02\n\rLapTrajectory\x12=\n\x08metadata\x18\x01 \x01(\x0b\x32+.IRacingTools.Models.LapTrajectory.Metadata\x12G\n\x15track_layout_metadata\x18\x02 \x01(\x0b\x32(.IRacingTools.Models.TrackLayoutMetadata\x12\x30\n\tfile_info\x18\x03 \x01(\x0b\x32\x1d.IRacingTools.Models.FileInfo\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x30\n\x04path\x18\x14 \x03(\x0b\x32\".IRacingTools.Models.LapCoordinate\x1aP\n\x08Metadata\x12\x0b\n\x03lap\x18\x01 \x01(\r\x12\x10\n\x08lap_time\x18\x02 \x01(\r\x12\x16\n\x0eincident_count\x18\x03 \x01(\r\x12\r\n\x05valid\x18\x04 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LapTrajectory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LAPTRAJECTORY']._serialized_start=109
  _globals['_LAPTRAJECTORY']._serialized_end=461
  _globals['_LAPTRAJECTORY_METADATA']._serialized_start=381
  _globals['_LAPTRAJECTORY_METADATA']._serialized_end=461
# @@protoc_insertion_point(module_scope)
