# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ScreenConfig.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Geometry_pb2 as Geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ScreenConfig.proto\x12\x16IRacingTools.Models.UI\x1a\x0eGeometry.proto\"\xe7\x01\n\rDisplayConfig\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07primary\x18\x05 \x01(\x08\x12\x34\n\rphysical_size\x18\n \x01(\x0b\x32\x1d.IRacingTools.Models.UI.SizeI\x12\r\n\x05scale\x18\x14 \x01(\x01\x12\x32\n\x0bscaled_size\x18\x15 \x01(\x0b\x32\x1d.IRacingTools.Models.UI.SizeI\x12\x32\n\x0bscaled_rect\x18\x16 \x01(\x0b\x32\x1d.IRacingTools.Models.UI.RectI\"\xb9\x01\n\x13\x44isplayLayoutConfig\x12\x30\n\x06origin\x18\x01 \x01(\x0b\x32 .IRacingTools.Models.UI.Position\x12\x37\n\rorigin_offset\x18\x02 \x01(\x0b\x32 .IRacingTools.Models.UI.Position\x12\x37\n\x08\x64isplays\x18\x05 \x03(\x0b\x32%.IRacingTools.Models.UI.DisplayConfig\"S\n\x0eVRLayoutConfig\x12\r\n\x05scale\x18\n \x01(\x01\x12\x32\n\x0bscaled_size\x18\x0b \x01(\x0b\x32\x1d.IRacingTools.Models.UI.SizeI\"\x87\x02\n\x0cScreenConfig\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x30\n\x04kind\x18\x03 \x01(\x0e\x32\".IRacingTools.Models.UI.ScreenKind\x12+\n\x04size\x18\x06 \x01(\x0b\x32\x1d.IRacingTools.Models.UI.SizeI\x12>\n\x07\x64isplay\x18\n \x01(\x0b\x32+.IRacingTools.Models.UI.DisplayLayoutConfigH\x00\x12\x34\n\x02vr\x18\x0b \x01(\x0b\x32&.IRacingTools.Models.UI.VRLayoutConfigH\x00\x42\x08\n\x06layout*\'\n\nScreenKind\x12\x0e\n\nSK_MONITOR\x10\x00\x12\t\n\x05SK_VR\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ScreenConfig_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCREENKIND']._serialized_start=835
  _globals['_SCREENKIND']._serialized_end=874
  _globals['_DISPLAYCONFIG']._serialized_start=63
  _globals['_DISPLAYCONFIG']._serialized_end=294
  _globals['_DISPLAYLAYOUTCONFIG']._serialized_start=297
  _globals['_DISPLAYLAYOUTCONFIG']._serialized_end=482
  _globals['_VRLAYOUTCONFIG']._serialized_start=484
  _globals['_VRLAYOUTCONFIG']._serialized_end=567
  _globals['_SCREENCONFIG']._serialized_start=570
  _globals['_SCREENCONFIG']._serialized_end=833
# @@protoc_insertion_point(module_scope)
