"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import Geometry_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ScreenKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ScreenKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ScreenKind.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SK_MONITOR: _ScreenKind.ValueType  # 0
    SK_VR: _ScreenKind.ValueType  # 1

class ScreenKind(_ScreenKind, metaclass=_ScreenKindEnumTypeWrapper): ...

SK_MONITOR: ScreenKind.ValueType  # 0
SK_VR: ScreenKind.ValueType  # 1
global___ScreenKind = ScreenKind

@typing.final
class DisplayConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PRIMARY_FIELD_NUMBER: builtins.int
    PHYSICAL_SIZE_FIELD_NUMBER: builtins.int
    SCALE_FIELD_NUMBER: builtins.int
    SCALED_SIZE_FIELD_NUMBER: builtins.int
    SCALED_RECT_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    primary: builtins.bool
    scale: builtins.float
    @property
    def physical_size(self) -> Geometry_pb2.SizeI: ...
    @property
    def scaled_size(self) -> Geometry_pb2.SizeI: ...
    @property
    def scaled_rect(self) -> Geometry_pb2.RectI: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        primary: builtins.bool = ...,
        physical_size: Geometry_pb2.SizeI | None = ...,
        scale: builtins.float = ...,
        scaled_size: Geometry_pb2.SizeI | None = ...,
        scaled_rect: Geometry_pb2.RectI | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["physical_size", b"physical_size", "scaled_rect", b"scaled_rect", "scaled_size", b"scaled_size"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name", "physical_size", b"physical_size", "primary", b"primary", "scale", b"scale", "scaled_rect", b"scaled_rect", "scaled_size", b"scaled_size"]) -> None: ...

global___DisplayConfig = DisplayConfig

@typing.final
class DisplayLayoutConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORIGIN_FIELD_NUMBER: builtins.int
    ORIGIN_OFFSET_FIELD_NUMBER: builtins.int
    DISPLAYS_FIELD_NUMBER: builtins.int
    @property
    def origin(self) -> Geometry_pb2.Position: ...
    @property
    def origin_offset(self) -> Geometry_pb2.Position: ...
    @property
    def displays(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DisplayConfig]: ...
    def __init__(
        self,
        *,
        origin: Geometry_pb2.Position | None = ...,
        origin_offset: Geometry_pb2.Position | None = ...,
        displays: collections.abc.Iterable[global___DisplayConfig] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["origin", b"origin", "origin_offset", b"origin_offset"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["displays", b"displays", "origin", b"origin", "origin_offset", b"origin_offset"]) -> None: ...

global___DisplayLayoutConfig = DisplayLayoutConfig

@typing.final
class VRLayoutConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCALE_FIELD_NUMBER: builtins.int
    SCALED_SIZE_FIELD_NUMBER: builtins.int
    scale: builtins.float
    @property
    def scaled_size(self) -> Geometry_pb2.SizeI: ...
    def __init__(
        self,
        *,
        scale: builtins.float = ...,
        scaled_size: Geometry_pb2.SizeI | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["scaled_size", b"scaled_size"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["scale", b"scale", "scaled_size", b"scaled_size"]) -> None: ...

global___VRLayoutConfig = VRLayoutConfig

@typing.final
class ScreenConfig(google.protobuf.message.Message):
    """*
    Represents a complete screen
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    DISPLAY_FIELD_NUMBER: builtins.int
    VR_FIELD_NUMBER: builtins.int
    id: builtins.str
    """*
    Must serve as a hash
    """
    name: builtins.str
    kind: global___ScreenKind.ValueType
    @property
    def size(self) -> Geometry_pb2.SizeI: ...
    @property
    def display(self) -> global___DisplayLayoutConfig: ...
    @property
    def vr(self) -> global___VRLayoutConfig: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        kind: global___ScreenKind.ValueType = ...,
        size: Geometry_pb2.SizeI | None = ...,
        display: global___DisplayLayoutConfig | None = ...,
        vr: global___VRLayoutConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["display", b"display", "layout", b"layout", "size", b"size", "vr", b"vr"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["display", b"display", "id", b"id", "kind", b"kind", "layout", b"layout", "name", b"name", "size", b"size", "vr", b"vr"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["layout", b"layout"]) -> typing.Literal["display", "vr"] | None: ...

global___ScreenConfig = ScreenConfig
