"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import Pipeline_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TelemetryDataFile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TelemetryDataFile._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATUS_CREATED: TelemetryDataFile._Status.ValueType  # 0
        STATUS_AVAILABLE: TelemetryDataFile._Status.ValueType  # 5
        STATUS_INVALID: TelemetryDataFile._Status.ValueType  # 10
        STATUS_ERROR: TelemetryDataFile._Status.ValueType  # 20

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_CREATED: TelemetryDataFile.Status.ValueType  # 0
    STATUS_AVAILABLE: TelemetryDataFile.Status.ValueType  # 5
    STATUS_INVALID: TelemetryDataFile.Status.ValueType  # 10
    STATUS_ERROR: TelemetryDataFile.Status.ValueType  # 20

    ID_FIELD_NUMBER: builtins.int
    ALIAS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    ERROR_DETAILS_FIELD_NUMBER: builtins.int
    PIPELINES_FIELD_NUMBER: builtins.int
    id: builtins.str
    alias: builtins.str
    status: global___TelemetryDataFile.Status.ValueType
    created_at: builtins.int
    updated_at: builtins.int
    filename: builtins.str
    error_details: builtins.str
    @property
    def pipelines(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Pipeline_pb2.Pipeline]:
        """Pipeline (i.e. TRACK_MAP)"""

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        alias: builtins.str = ...,
        status: global___TelemetryDataFile.Status.ValueType = ...,
        created_at: builtins.int = ...,
        updated_at: builtins.int = ...,
        filename: builtins.str = ...,
        error_details: builtins.str = ...,
        pipelines: collections.abc.Iterable[Pipeline_pb2.Pipeline] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["alias", b"alias", "created_at", b"created_at", "error_details", b"error_details", "filename", b"filename", "id", b"id", "pipelines", b"pipelines", "status", b"status", "updated_at", b"updated_at"]) -> None: ...

global___TelemetryDataFile = TelemetryDataFile
