# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TelemetryData.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Pipeline_pb2 as Pipeline__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13TelemetryData.proto\x12\x1dIRacingTools.Models.Telemetry\x1a\x0ePipeline.proto\"\xd4\x02\n\x11TelemetryDataFile\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x61lias\x18\x02 \x01(\t\x12G\n\x06status\x18\x03 \x01(\x0e\x32\x37.IRacingTools.Models.Telemetry.TelemetryDataFile.Status\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\x12\x12\n\nupdated_at\x18\x06 \x01(\x03\x12\x10\n\x08\x66ilename\x18\n \x01(\t\x12\x15\n\rerror_details\x18\x14 \x01(\t\x12\x30\n\tpipelines\x18\x32 \x03(\x0b\x32\x1d.IRacingTools.Models.Pipeline\"X\n\x06Status\x12\x12\n\x0eSTATUS_CREATED\x10\x00\x12\x14\n\x10STATUS_AVAILABLE\x10\x05\x12\x12\n\x0eSTATUS_INVALID\x10\n\x12\x10\n\x0cSTATUS_ERROR\x10\x14\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TelemetryData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TELEMETRYDATAFILE']._serialized_start=71
  _globals['_TELEMETRYDATAFILE']._serialized_end=411
  _globals['_TELEMETRYDATAFILE_STATUS']._serialized_start=323
  _globals['_TELEMETRYDATAFILE_STATUS']._serialized_end=411
# @@protoc_insertion_point(module_scope)
