"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import FileInfo_pb2
import TrackLayoutMetadata_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TelemetryDataFile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TelemetryDataFile._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATUS_CREATED: TelemetryDataFile._Status.ValueType  # 0
        STATUS_AVAILABLE: TelemetryDataFile._Status.ValueType  # 5
        STATUS_INVALID: TelemetryDataFile._Status.ValueType  # 10
        STATUS_ERROR: TelemetryDataFile._Status.ValueType  # 20

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_CREATED: TelemetryDataFile.Status.ValueType  # 0
    STATUS_AVAILABLE: TelemetryDataFile.Status.ValueType  # 5
    STATUS_INVALID: TelemetryDataFile.Status.ValueType  # 10
    STATUS_ERROR: TelemetryDataFile.Status.ValueType  # 20

    ID_FIELD_NUMBER: builtins.int
    ALIAS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    TRACK_LAYOUT_METADATA_FIELD_NUMBER: builtins.int
    FILE_INFO_FIELD_NUMBER: builtins.int
    ERROR_DETAILS_FIELD_NUMBER: builtins.int
    id: builtins.str
    alias: builtins.str
    status: global___TelemetryDataFile.Status.ValueType
    error_details: builtins.str
    @property
    def track_layout_metadata(self) -> TrackLayoutMetadata_pb2.TrackLayoutMetadata:
        """*
        Track Layout ID
        """

    @property
    def file_info(self) -> FileInfo_pb2.FileInfo: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        alias: builtins.str = ...,
        status: global___TelemetryDataFile.Status.ValueType = ...,
        track_layout_metadata: TrackLayoutMetadata_pb2.TrackLayoutMetadata | None = ...,
        file_info: FileInfo_pb2.FileInfo | None = ...,
        error_details: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["file_info", b"file_info", "track_layout_metadata", b"track_layout_metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["alias", b"alias", "error_details", b"error_details", "file_info", b"file_info", "id", b"id", "status", b"status", "track_layout_metadata", b"track_layout_metadata"]) -> None: ...

global___TelemetryDataFile = TelemetryDataFile
