# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TelemetryDataFile.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FileInfo_pb2 as FileInfo__pb2
import TrackLayoutMetadata_pb2 as TrackLayoutMetadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17TelemetryDataFile.proto\x12\x13IRacingTools.Models\x1a\x0e\x46ileInfo.proto\x1a\x19TrackLayoutMetadata.proto\"\xd9\x02\n\x11TelemetryDataFile\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x61lias\x18\x02 \x01(\t\x12=\n\x06status\x18\x03 \x01(\x0e\x32-.IRacingTools.Models.TelemetryDataFile.Status\x12G\n\x15track_layout_metadata\x18\x05 \x01(\x0b\x32(.IRacingTools.Models.TrackLayoutMetadata\x12\x30\n\tfile_info\x18\n \x01(\x0b\x32\x1d.IRacingTools.Models.FileInfo\x12\x15\n\rerror_details\x18\x14 \x01(\t\"X\n\x06Status\x12\x12\n\x0eSTATUS_CREATED\x10\x00\x12\x14\n\x10STATUS_AVAILABLE\x10\x05\x12\x12\n\x0eSTATUS_INVALID\x10\n\x12\x10\n\x0cSTATUS_ERROR\x10\x14\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TelemetryDataFile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TELEMETRYDATAFILE']._serialized_start=92
  _globals['_TELEMETRYDATAFILE']._serialized_end=437
  _globals['_TELEMETRYDATAFILE_STATUS']._serialized_start=349
  _globals['_TELEMETRYDATAFILE_STATUS']._serialized_end=437
# @@protoc_insertion_point(module_scope)
