# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrackMap.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Geometry_pb2 as Geometry__pb2
import LapCoordinate_pb2 as LapCoordinate__pb2
import TrackLayoutMetadata_pb2 as TrackLayoutMetadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eTrackMap.proto\x12\x13IRacingTools.Models\x1a\x0eGeometry.proto\x1a\x13LapCoordinate.proto\x1a\x19TrackLayoutMetadata.proto\"\x8e\x02\n\x08TrackMap\x12G\n\x15track_layout_metadata\x18\x01 \x01(\x0b\x32(.IRacingTools.Models.TrackLayoutMetadata\x12\x16\n\x0etotal_distance\x18\x02 \x01(\x02\x12\x30\n\x04path\x18\n \x03(\x0b\x32\".IRacingTools.Models.LapCoordinate\x12(\n\x04size\x18\x14 \x01(\x0b\x32\x1a.IRacingTools.Models.SizeF\x12/\n\x0bscaled_size\x18\x15 \x01(\x0b\x32\x1a.IRacingTools.Models.SizeF\x12\x14\n\x0cscaled_ratio\x18\x16 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TrackMap_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRACKMAP']._serialized_start=104
  _globals['_TRACKMAP']._serialized_end=374
# @@protoc_insertion_point(module_scope)
