"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import FileInfo_pb2
import Pipeline_pb2
import TrackLayoutMetadata_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TrackMapFile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TrackMapFile._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATUS_CREATED: TrackMapFile._Status.ValueType  # 0
        STATUS_PROCESSING: TrackMapFile._Status.ValueType  # 1
        STATUS_AVAILABLE: TrackMapFile._Status.ValueType  # 5
        STATUS_INVALID: TrackMapFile._Status.ValueType  # 10
        STATUS_ERROR: TrackMapFile._Status.ValueType  # 20

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_CREATED: TrackMapFile.Status.ValueType  # 0
    STATUS_PROCESSING: TrackMapFile.Status.ValueType  # 1
    STATUS_AVAILABLE: TrackMapFile.Status.ValueType  # 5
    STATUS_INVALID: TrackMapFile.Status.ValueType  # 10
    STATUS_ERROR: TrackMapFile.Status.ValueType  # 20

    TRACK_LAYOUT_METADATA_FIELD_NUMBER: builtins.int
    FILE_INFO_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PIPELINES_FIELD_NUMBER: builtins.int
    ERROR_DETAILS_FIELD_NUMBER: builtins.int
    status: global___TrackMapFile.Status.ValueType
    error_details: builtins.str
    @property
    def track_layout_metadata(self) -> TrackLayoutMetadata_pb2.TrackLayoutMetadata:
        """*
        Track Layout ID
        """

    @property
    def file_info(self) -> FileInfo_pb2.FileInfo: ...
    @property
    def pipelines(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Pipeline_pb2.Pipeline]:
        """Pipeline (i.e. TRACK_MAP)"""

    def __init__(
        self,
        *,
        track_layout_metadata: TrackLayoutMetadata_pb2.TrackLayoutMetadata | None = ...,
        file_info: FileInfo_pb2.FileInfo | None = ...,
        status: global___TrackMapFile.Status.ValueType = ...,
        pipelines: collections.abc.Iterable[Pipeline_pb2.Pipeline] | None = ...,
        error_details: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["file_info", b"file_info", "track_layout_metadata", b"track_layout_metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error_details", b"error_details", "file_info", b"file_info", "pipelines", b"pipelines", "status", b"status", "track_layout_metadata", b"track_layout_metadata"]) -> None: ...

global___TrackMapFile = TrackMapFile
