# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrackLayoutMetadata.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TrackMetadata_pb2 as TrackMetadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19TrackLayoutMetadata.proto\x12\x13IRacingTools.Models\x1a\x13TrackMetadata.proto\"k\n\x13TrackLayoutMetadata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12:\n\x0etrack_metadata\x18\x05 \x01(\x0b\x32\".IRacingTools.Models.TrackMetadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TrackLayoutMetadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRACKLAYOUTMETADATA']._serialized_start=71
  _globals['_TRACKLAYOUTMETADATA']._serialized_end=178
# @@protoc_insertion_point(module_scope)
