@startuml





/' Objects '/

class fmt::formatterE,std::enable_if_tstd::is_enum_vE <template<typename E>> {
	+format(const E& enumValue, fmt::format_context& ctx) : auto {query}
}


namespace IRacingTools {
	namespace Shared {
		class DiskSessionDataProvider {
			+DiskSessionDataProvider(const std::filesystem::path& file, IRacingSDK::ClientId clientId, const std::optional<Options>& options)
			+~DiskSessionDataProvider()
			-clientId_ : IRacingSDK::ClientId
			+getDataVariableHeaders() : IRacingSDK::VarHeaders&
			+getSessionTiming() : Models::Session::SessionTiming
			-options_ : Options
			+options() : Options&
			+isAvailable() : bool
			+isControllable() : bool {query}
			+isLive() : bool {query}
			+isPaused() : bool
			+isRunning() : bool
			+pause() : bool
			+resume() : bool
			+seek(std::size_t sampleIndex) : bool
			+seekToSubSession(std::int32_t subSessionNum) : bool
			+start() : bool
			-updateSessionTiming() : bool
			-file_ : std::filesystem::path
			+sessionTickCount() : std::optional<std::int32_t>
			+sessionTicks() : std::optional<std::int32_t>
			+clientProvider() : std::shared_ptr<IRacingSDK::ClientProvider>
			-diskClient_ : std::shared_ptr<IRacingSDK::DiskClient>
			+sessionInfo() : std::shared_ptr<IRacingSDK::SessionInfo::SessionInfoMessage>
			+getSessionEventData(Models::RPC::Events::SessionEventType type) : std::shared_ptr<Models::RPC::Events::SessionEventData>
			+getSessionMetadata(bool includeSessionInfoYaml) : std::shared_ptr<Models::Session::SessionMetadata>
			+sampleCount() : std::size_t
			+sampleIndex() : std::size_t
			+id() : std::string
			+sessionInfoStr() : std::string
			-checkConnection() : void
			-fireDataUpdatedEvent() : void
			-fireMetadataChangedEvent() : void
			-fireSessionChangedEvent() : void
			-init() : void
			-process() : void
			#runnable() : void
			+setOptions(Options newOptions) : void
			+stop() : void
			-updateSessionDataFrame() : void
			-updateSessionMetadata() : void
		}

		class LiveSessionDataProvider {
			+LiveSessionDataProvider()
			+~LiveSessionDataProvider()
			+getDataVariableHeaders() : IRacingSDK::VarHeaders&
			+getSessionTiming() : Models::Session::SessionTiming
			+isAvailable() : bool
			+isControllable() : bool {query}
			+isLive() : bool {query}
			+isPaused() : bool
			+isRunning() : bool
			+pause() : bool
			+resume() : bool
			+start() : bool
			-waitForDataDuration() : std::int64_t
			+sessionTickCount() : std::optional<std::int32_t>
			+sessionTicks() : std::optional<std::int32_t>
			+clientProvider() : std::shared_ptr<IRacingSDK::ClientProvider>
			+sessionInfo() : std::shared_ptr<IRacingSDK::SessionInfo::SessionInfoMessage>
			+getSessionEventData(Models::RPC::Events::SessionEventType type) : std::shared_ptr<Models::RPC::Events::SessionEventData>
			+getSessionMetadata(bool includeSessionInfoYaml) : std::shared_ptr<Models::Session::SessionMetadata>
			+id() : std::string
			+sessionInfoStr() : std::string
			-checkConnection() : void
			-init() : void
			-process() : void
			-processData() : void
			#runnable() : void
			+stop() : void
			-updateSessionTiming() : void
		}

		abstract class SessionDataProvider {
			+~SessionDataProvider()
			+{abstract} getDataVariableHeaders() : IRacingSDK::VarHeaders&
			+{abstract} getSessionTiming() : Models::Session::SessionTiming
			+{abstract} isAvailable() : bool
			+{abstract} isControllable() : bool {query}
			+{abstract} isLive() : bool {query}
			+{abstract} isPaused() : bool
			+{abstract} isRunning() : bool
			+{abstract} pause() : bool
			+{abstract} resume() : bool
			+seek(std::size_t sampleIndex) : bool
			+{abstract} start() : bool
			+{abstract} sessionTickCount() : std::optional<std::int32_t>
			+{abstract} sessionTicks() : std::optional<std::int32_t>
			+{abstract} clientProvider() : std::shared_ptr<IRacingSDK::ClientProvider>
			+{abstract} sessionInfo() : std::shared_ptr<IRacingSDK::SessionInfo::SessionInfoMessage>
			+{abstract} getSessionEventData(Models::RPC::Events::SessionEventType type) : std::shared_ptr<Models::RPC::Events::SessionEventData>
			+{abstract} getSessionMetadata(bool includeSessionInfoYaml) : std::shared_ptr<Models::Session::SessionMetadata>
			+sampleCount() : std::size_t
			+sampleIndex() : std::size_t
			+{abstract} id() : std::string
			+{abstract} sessionInfoStr() : std::string
			+{abstract} stop() : void
		}

		enum Rect::Origin {
			BottomLeft
			TopLeft
		}

		enum ScaleToFitMode {
			GrowOnly
			ShrinkOnly
			ShrinkOrGrow
		}

		class DiskSessionDataProvider::Options {
		}

		class FileTimestamps <template<typename Clock=DefaultFileClock>> {
			+createdAt : time_point<Clock>
			+modifiedAt : time_point<Clock>
		}

		class Point <template<class T>> {
			+operatorD2D1_POINT_2F() {query}
			+operatorD2D1_POINT_2U() {query}
			+operator*(const T operand) : Point<T> {query}
			+operator+(Point<T> lhs, const Point<T>& rhs) : Point<T>
			+operator/(const T divisor) : Point<T> {query}
			+operator+=(const Point<T>& operand) : Point<T>&
			+staticCast() : TPoint {query}
			+operator<=>(const Point<T> &) : auto {query}
			+x() : auto {query}
			+y() : auto {query}
			+rounded() : requires std::floating_point<T>TPoint {query}
		}

		class Rect <template<class T>> {
			+operatorD2D1_RECT_F() {query}
			+operatorD2D_RECT_U() {query}
			+operatorD3D11_RECT() {query}
			+operatorbool() {query}
			+bottomRight() : Point<T> {query}
			+offset() : Point<T> {query}
			+topLeft() : Point<T> {query}
			+operator*(const TValue operand) : Rect<T> {query}
			+operator/(const T divisor) : Rect<T> {query}
			+withOrigin(Origin otherOrigin, const Size<T>& container) : Rect<T> {query}
			+size() : Size<T> {query}
			+staticCast() : TRect {query}
			+staticCastWithBottomRight() : TRect {query}
			+bottom() : auto {query}
			+height() : auto {query}
			+left() : auto {query}
			+operator<=>(const Rect<T> &) : auto {query}
			+right() : auto {query}
			+top() : auto {query}
			+width() : auto {query}
			+origin() : int {query}
			+operator*(const TValue operand) : requires std :: floating_point<T>Rect<T> {query}
			+rounded() : requires std::floating_point<T>Rect<TValue> {query}
		}

		class Size <template<class T>> {
			+Size(const T& width, const T& height)
			+operatorD2D1_SIZE_F() {query}
			+operatorD2D1_SIZE_U() {query}
			+operatorbool() {query}
			+requires(std::integral<T>| | std::floating_point<TValue>) constexpr TSize staticCast () {query}
			+string() {query}
			+integerScaledToFit(const Size<T>& container, ScaleToFitMode mode) : Size<T> {query}
			+operator*(const std::integral auto operand) : Size<T> {query}
			+operator*(const std::floating_point auto operand) : Size<T> {query}
			+operator/(const T divisor) : Size<T> {query}
			+scaledToFit(const Size<T>& container, ScaleToFitMode mode) : Size<T> {query}
			+height() : T {query}
			+width() : T {query}
			+floor() : TSize {query}
			+height() : auto {query}
			+operator<=>(const Size<T> &) : auto {query}
			+width() : auto {query}
			+operator==(const Size& other) : bool {query}
			+rounded() : requires std::floating_point<T>TSize {query}
			+toString() : std::string {query}
		}

		namespace VR {
			enum VRRenderConfig::Quirks::Upscaling {
				AlwaysOff
				AlwaysOn
				Automatic
			}

			class GazeTargetScale {
				+operator<=>(const GazeTargetScale &) : auto {query}
			}

			class VRNativeLayout {
				+operator<=>(const VRNativeLayout &) : auto {query}
				+operator==(const VRNativeLayout& other) : auto {query}
			}

			class VRNativePose {
				+getHorizontalMirror() : VRNativePose {query}
				+operator<=>(const VRNativePose &) : auto {query}
				+operator==(const VRNativePose& other) : auto {query}
				+isValid() : bool {query}
				+rX : float
				+rX : float
				+rX : float
				+x : float
				+x : float
				+x : float
				+x : float
				+x : float
				+x : float
			}

			class VROpacityConfig {
				+operator<=>(const VROpacityConfig &) : auto {query}
			}

			class VROverlayFrameRenderConfig {
				+layout : VRNativeLayout
				+zoomScale : float
			}

			class VRRenderConfig {
				+operator<=>(const VRRenderConfig &) : auto {query}
				+recenterCount : uint64_t
			}

			class VRRenderConfig::Quirks {
				+operator<=>(Quirks &) : auto {query}
			}
		}

		namespace Utils {
			class COMException {
				+COMException(HRESULT hr)
				+getResult() : HRESULT {query}
				-result : HRESULT
				+what() : char* {query}
			}

			abstract class Controllable {
				+Controllable()
				+~Controllable()
				+{abstract} init() : std::expected<bool , IRacingSDK::GeneralError>
				+{abstract} start() : std::expected<bool , IRacingSDK::GeneralError>
				+{abstract} destroy() : std::optional<IRacingSDK::GeneralError>
			}

			class JSONLinesMessageFileHandler <template<typename MessageClazz>> {
				+JSONLinesMessageFileHandler(const fs::path& file)
				+~JSONLinesMessageFileHandler()
				+file() : fs::path
				-file_ : fs::path
				+write(const std::vector<std::shared_ptr<MessageClazz>>& messages) : std::expected<std::size_t , GeneralError>
				+read() : std::expected<std::vector<std::shared_ptr<MessageClazz>>, GeneralError>
				+clear() : std::optional<GeneralError>
			}

			class RingQueue <template<typename T, std::size_t Size>> {
				+RingQueue()
				+~RingQueue()
				+empty() : bool
				+full() : bool
				+push(const T& item) : bool
				-full_ : std::atomic_bool
				+front() : std::optional<T> {query}
				+pop() : std::optional<T>
				+capacity() : std::size_t {query}
				-head_ : std::size_t
				+size() : std::size_t {query}
				-tail_ : std::size_t
				+clear(T value) : void
				+destroy() : void
			}

			class HandleCloser {
				+operator()(HANDLE h) : void
			}

			class JSONLinesMessageFileHandler::anon_struct_1 {
			}

			class PrettyType <template<typename T>> {
				+name() : std::string
			}

			class PrettyTypeId {
				+toString() : std::string {query}
			}

			class VirtualDeleter {
				+operator()(void* p) : void
			}
		}

		namespace UI {
			class BaseWindow <template<class WindowClazz>> {
				+BaseWindow()
				+~BaseWindow()
				+events : <anon-struct-1>
				+getCreateOptions() : CreateOptions
				+windowHandle() : HWND {query}
				#handleMessage(UINT messageType, WPARAM wParam, LPARAM lParam) : LRESULT
				+{static} WindowProc(HWND windowHandle, UINT messageType, WPARAM wParam, LPARAM lParam) : LRESULT CALLBACK
				+getSize() : Size<UINT>
				+getWindowClassOptions() : WNDCLASSEXW
				+create(const CreateOptions& options) : bool
				+createResources() : bool
				+isCreated() : bool
				+isReady() : bool
				#defaultHandleMessage(UINT messageType, WPARAM wParam, LPARAM lParam) : std::optional<LRESULT>
				+configureWindowClass(WNDCLASSEX& wc) : void
				+hide() : void
				+initialize() : void
				#onResize(const PixelSize& newSize, const PixelSize& oldSize) : void
				+show() : void
			}

			abstract class IViewerWindowRenderer {
				+~IViewerWindowRenderer()
				+{abstract} getSHM() : SHM::SHMCachedReader*
				+{abstract} getName() : std::wstring_view {query}
				+{abstract} render(SHM::IPCClientTexture* sourceTexture, const std::vector<std::pair<PixelRect, PixelRect>>& sourceDestRects, HANDLE destTexture, const PixelSize& destTextureDimensions, HANDLE fence, uint64_t fenceValueIn) : uint64_t
				+{abstract} initialize(uint8_t swapchainLength) : void
				+{abstract} saveTextureToFile(SHM::IPCClientTexture*, const std::filesystem::path &) : void
			}

			abstract class NormalWindow <template<typename WindowClazz>> {
				+NormalWindow()
				+~NormalWindow()
				#handleMessage(UINT messageType, WPARAM wParam, LPARAM lParam) : LRESULT
				+getWindowClassOptions() : WNDCLASSEX
				+getCreateOptions() : Window::CreateOptions
				+createResources() : bool
				+isReady() : bool
				-{static} FPS_60 : static constexpr UINT
				-{static} RenderTimerId : static constexpr UINT
				#dxr() : std::shared_ptr<Graphics::DXResources>&
				#dxwr() : std::shared_ptr<Graphics::DXWindowResources>&
				+paint() : void
				#{abstract} render(const std::shared_ptr<Graphics::RenderTarget>& target) : void
			}

			class ViewerWindow <template<Graphics::GraphicsPlatform GP>> {
				+{static} ClassName() : PCWSTR
				#getDestRect(const uint32_t offsetX, const Size<uint32_t> imageSize, const float scale) : PixelRect
				+createResources() : bool
				-{static} L : inline static auto
				#createTargetResources(const std::shared_ptr<Graphics::RenderTarget>& target) : void
				#render(const std::shared_ptr<Graphics::RenderTarget>& target) : void
				+resetTargetResources() : void
			}

			class ViewerWindowD3D11Renderer {
				+ViewerWindowD3D11Renderer(const winrt::com_ptr<ID3D11Device> &)
				+~ViewerWindowD3D11Renderer()
				-destDimensions_ : PixelSize
				+getSHM() : SHM::SHMCachedReader*
				-spriteBatch_ : std::unique_ptr<Graphics::SpriteBatch>
				+getName() : std::wstring_view {query}
				+render(SHM::IPCClientTexture* sourceTexture, const std::vector<std::pair<PixelRect, PixelRect>>& sourceDestRects, HANDLE destTexture, const PixelSize& destTextureDimensions, HANDLE fence, uint64_t fenceValueIn) : uint64_t
				+initialize(uint8_t swapchainLength) : void
				+saveTextureToFile(SHM::IPCClientTexture*, const std::filesystem::path &) : void
				-d3dDevice_ : winrt::com_ptr<ID3D11Device1>
				-d3dDeviceContext_ : winrt::com_ptr<ID3D11DeviceContext>
				-destRenderTargetView_ : winrt::com_ptr<ID3D11RenderTargetView>
				-destTexture_ : winrt::com_ptr<ID3D11Texture2D>
			}

			class Window {
				+Window()
				+~Window()
				+{static} DefaultWindowMessageLoop() : void
				+{static} PeekWindowMessageLoop(function<void ( MSG& )> callback) : void
			}

			enum ViewerAlignment {
				Bottom
				BottomLeft
				BottomRight
				Center
				Left
				Right
				Top
				TopLeft
				TopRight
			}

			enum ViewerFillMode {
				Checkerboard
				Default
				Transparent
			}

			class BaseWindow::anon_struct_1 {
			}

			class ViewerSettings {
				+{static} Load() : ViewerSettings
				+operator<=>(const ViewerSettings &) : auto {query}
				+save() : void
			}

			class Window::CreateOptions {
			}
		}

		namespace System {
			class DisplayInfo {
				+toModel() : Models::DisplayConfig {query}
				+toModel(Models::DisplayConfig* display) : Models::DisplayConfig* {query}
				+{static} EqualTo(const Models::DisplayConfig& d1, const Models::DisplayConfig& d2) : bool
				+{static} EqualTo(const DisplayInfo& di1, const DisplayInfo& di2) : bool
				+equalTo(const Models::DisplayConfig& display) : bool {query}
				+toString() : std::string {query}
			}

			class DisplayScreenInfo {
				+{static} create(const std::vector<DisplayInfo>& displays) : DisplayScreenInfo
				+{static} generate() : IRacingSDK::Expected<DisplayScreenInfo>
				+toModel() : Models::ScreenConfig {query}
				+toModel(Models::ScreenConfig* screen) : Models::ScreenConfig* {query}
				+equalTo(const DisplayScreenInfo& other) : bool {query}
				+equalTo(const Models::ScreenConfig &) : bool {query}
				+toString() : std::string {query}
			}

			class VRScreenInfo {
				+{static} generate() : IRacingSDK::Expected<VRScreenInfo>
				+toModel() : Models::ScreenConfig {query}
				+toModel(Models::ScreenConfig* screen) : Models::ScreenConfig* {query}
				+equalTo(const VRScreenInfo& other) : bool {query}
				+equalTo(const Models::ScreenConfig &) : bool {query}
				+toString() : std::string {query}
			}
		}

		namespace Services {
			class IRacingIPCServer {
				+IRacingIPCServer(const std::shared_ptr<ServiceContainer>& serviceContainer)
				+IRacingIPCServer(const std::shared_ptr<ServiceContainer>& serviceContainer, Options options)
				+execute(const IPC::Envelope& messageIn) : IPC::Envelope
				-options_ : Options
				+init() : std::expected<bool , IRacingSDK::GeneralError>
				+setDataProvider(const std::shared_ptr<SessionDataProvider>& dataProvider) : std::expected<bool , IRacingSDK::GeneralError>
				+start() : std::expected<bool , IRacingSDK::GeneralError>
				-clientMessageEventHandlerMap_ : std::map<RPC::Events::SessionEventType, ClientMessageEventHandlerFn>
				-clientMessageRequestHandlerMap_ : std::map<RPC::IR::IRacingIPCMessageType, ClientMessageRequestHandlerFn>
				+destroy() : std::optional<IRacingSDK::GeneralError>
				+getClientMetadata(std::uint32_t id) : std::shared_ptr<RPC::IR::IRacingIPCClientMetadata>
				+addRoute(const std::shared_ptr<IPC::NamedPipeServerRoute>& route) : void
				+onSessionEvent(Models::RPC::Events::SessionEventType eventType, const std::shared_ptr<IRacingSDK::ClientProvider>& sessionClientProvider, const std::shared_ptr<SessionDataProvider>& dataProvider) : void
				+removeDataProvider() : void
				+setClientMetadata(std::uint32_t id, const std::shared_ptr<RPC::IR::IRacingIPCClientMetadata>& metadata) : void
			}

			class LapTrajectoryTool {
				+createLapTrajectory(const std::filesystem::path& file, CreateOptions options) : std::expected<std::shared_ptr<Models::LapTrajectory>, GeneralError>
				+createLapTrajectory(const std::shared_ptr<IRacingSDK::DiskClient>& client, CreateOptions options) : std::expected<std::shared_ptr<Models::LapTrajectory>, GeneralError>
			}

			class RPCServerService {
				+RPCServerService(const std::shared_ptr<ServiceContainer>& serviceContainer)
				+RPCServerService(const std::shared_ptr<ServiceContainer>& serviceContainer, Options options)
				+events : <anon-struct-1>
				+execute(shared_ptr<Models::RPC::Envelope> messageIn) : Envelope
				-options_ : Options
				+init() : std::expected<bool , IRacingSDK::GeneralError>
				+start() : std::expected<bool , IRacingSDK::GeneralError>
				+destroy() : std::optional<IRacingSDK::GeneralError>
				+addRoute(const std::shared_ptr<Route>& route) : void
			}

			abstract class RPCServerService::Route {
				+Route(const std::string& matchExpression)
				+~Route()
				+accepts(const std::string& path) : bool
				+{abstract} execute(shared_ptr<Models::RPC::Envelope> messageIn, shared_ptr<Models::RPC::Envelope> messageOut) : std::expected<Envelope , IRacingSDK::GeneralError>
				-matcher_ : std::regex
				-matchExpression_ : std::string
			}

			class RPCServerService::TypedRoute <template<typename RequestType, typename ResponseType>> {
				+TypedRoute(function<std::expected<std::shared_ptr<ResponseType>, IRacingSDK::GeneralError>( const std::shared_ptr<RequestType>&, const std::shared_ptr<RPC::Envelope>& )> executor, const std::string& matchExpression)
				-executor_ : function<std::expected<std::shared_ptr<ResponseType>, IRacingSDK::GeneralError>( const std::shared_ptr<RequestType>&, const std::shared_ptr<RPC::Envelope>& )>
				+execute(shared_ptr<Models::RPC::Envelope> messageIn, shared_ptr<Models::RPC::Envelope> messageOut) : std::expected<Envelope , IRacingSDK::GeneralError>
				+{static} Create(function<std::expected<std::shared_ptr<ResponseType>, IRacingSDK::GeneralError>( const std::shared_ptr<RequestType>&, const std::shared_ptr<RPC::Envelope>& )> executor, const std::string& matchExpression) : std::shared_ptr<TypedRoute>
			}

			class Service {
				#Service(const std::shared_ptr<ServiceContainer>& serviceContainer, const std::string& name)
				+~Service()
				#setState(ServiceState newState) : State
				+state() : State {query}
				+isRunning() : bool
				-serviceContainer_ : const std::shared_ptr<ServiceContainer>
				+init() : std::expected<bool , IRacingSDK::GeneralError>
				+start() : std::expected<bool , IRacingSDK::GeneralError>
				+destroy() : std::optional<IRacingSDK::GeneralError>
				+getContainer() : std::shared_ptr<ServiceContainer> {query}
				+name() : std::string {query}
				-name_ : std::string
			}

			class ServiceContainer {
				+~ServiceContainer()
				+getService(const std::optional<std::string>& nameOrType) : std::shared_ptr<ServiceType>
				#setService(const std::shared_ptr<ServiceType>& service) : void
			}

			class ServiceManager <template<typename ... ServiceTypes>> {
				+ServiceManager()
				+~ServiceManager()
				+setState(ServiceState newState) : State
				+state() : State {query}
				+isRunning() : bool {query}
				+{static} ServiceCount : static constexpr std::size_t
				+destroy() : std::optional<IRacingSDK::GeneralError>
				+init() : std::optional<IRacingSDK::GeneralError>
				+start() : std::optional<IRacingSDK::GeneralError>
				+wait(bool waitEvenIfNotRunning) : std::optional<IRacingSDK::GeneralError>
				-createServices() : void
			}

			class SessionManagerService {
				+SessionManagerService(const std::shared_ptr<ServiceContainer>& serviceContainer)
				+~SessionManagerService()
				+events : <anon-struct-1>
				+exists(const std::string& sessionId) : bool
				+{static} LiveSessionId : static constexpr std::string_view
				+init() : std::expected<bool , IRacingSDK::GeneralError>
				+start() : std::expected<bool , IRacingSDK::GeneralError>
				+destroy() : std::optional<IRacingSDK::GeneralError>
				+remove(const std::string& sessionId) : std::shared_ptr<SessionDataProvider>
				+get(const std::string& sessionId) : std::shared_ptr<T>
				+set(const std::string& sessionId, const std::shared_ptr<T>& dataProvider) : std::shared_ptr<T>
				+size() : std::size_t
				+allOfType(Models::Session::SessionType type) : std::vector<std::shared_ptr<T>>
			}

			class TelemetryDataService {
				+TelemetryDataService(const std::shared_ptr<ServiceContainer>& serviceContainer)
				+TelemetryDataService(const std::shared_ptr<ServiceContainer>& serviceContainer, Options options)
				+~TelemetryDataService()
				+events : <anon-struct-1>
				-taskQueueFn(fs::path file, std::shared_ptr<TelemetryDataFile> dataFile) : TQReturnType
				+exists(const std::string& nameOrAlias) : bool
				+hasPendingTasks() : bool
				+isAvailable(const std::string& nameOrAlias) : bool
				+init() : std::expected<bool , IRacingSDK::GeneralError>
				+start() : std::expected<bool , IRacingSDK::GeneralError>
				+set(const std::shared_ptr<TelemetryDataFile>& dataFile, bool skipFileChangedEvent) : std::expected<const std::shared_ptr<TelemetryDataFile>, IRacingSDK::GeneralError>
				+set(const std::vector<std::shared_ptr<TelemetryDataFile>>& changedDataFiles, bool skipFileChangedEvent) : std::expected<const std::vector<std::shared_ptr<TelemetryDataFile>>, IRacingSDK::GeneralError>
				+save() : std::expected<std::shared_ptr<TelemetryDataService>, IRacingSDK::GeneralError>
				+getTrackLayoutMetadata(const std::shared_ptr<TelemetryDataFile>& dataFile) : std::expected<std::shared_ptr<TrackLayoutMetadata>, GeneralError>
				+getTrackLayoutMetadata(const fs::path& file) : std::expected<std::shared_ptr<TrackLayoutMetadata>, GeneralError>
				+clearTelemetryFileCache() : std::optional<IRacingSDK::GeneralError>
				+destroy() : std::optional<IRacingSDK::GeneralError>
				+load(bool reload) : std::optional<IRacingSDK::GeneralError>
				+findFile(const std::shared_ptr<TelemetryDataFile>& dataFile) : std::optional<fs::path>
				+get(const std::string& nameOrAlias) : std::shared_ptr<TelemetryDataFile>
				+getByFile(const fs::path& file) : std::shared_ptr<TelemetryDataFile>
				-enqueueFiles(const std::vector<fs::path>& files) : std::size_t
				+pendingTaskCount() : std::size_t
				+scanAllFiles(const std::optional<std::vector<std::filesystem::path>>& overrideFilePaths) : std::size_t
				+size() : std::size_t
				+listTelemetryFiles(const std::optional<std::vector<std::filesystem::path>>& overrideFilePaths) : std::vector<fs::path>
				+toList() : std::vector<std::shared_ptr<TelemetryDataFile>>
				+reset(bool skipPrepare) : void
				+setOptions(Options options) : void
			}

			class TelemetryFileHandler {
				+TelemetryFileHandler(const std::filesystem::path& file)
				+TelemetryFileHandler(const std::shared_ptr<IRacingSDK::DiskClient>& client)
				+getLapData(bool includeInvalidLaps) : std::expected<std::vector<LapDataWithPath>, GeneralError>
				-client_ : std::shared_ptr<IRacingSDK::DiskClient>
			}

			class TrackMapService {
				+TrackMapService(const std::shared_ptr<ServiceContainer>& serviceContainer)
				+TrackMapService(const std::shared_ptr<ServiceContainer>& serviceContainer, Options options)
				+~TrackMapService()
				+events : <anon-struct-2>
				+exists(const std::string& trackLayoutId) : bool
				+hasPendingTasks() : bool
				+isAvailable(const std::string& trackLayoutId) : bool
				+getFilePath() : fs::path
				+init() : std::expected<bool , IRacingSDK::GeneralError>
				+start() : std::expected<bool , IRacingSDK::GeneralError>
				+set(const std::shared_ptr<TrackMapFile>& tmFile) : std::expected<const std::shared_ptr<TrackMapFile>, IRacingSDK::GeneralError>
				+set(const std::string& trackLayoutId, const std::shared_ptr<TrackMapFile>& tmFile) : std::expected<const std::shared_ptr<TrackMapFile>, IRacingSDK::GeneralError>
				+save() : std::expected<std::shared_ptr<TrackMapService>, IRacingSDK::GeneralError>
				+clearTrackMapCache() : std::optional<IRacingSDK::GeneralError>
				+destroy() : std::optional<IRacingSDK::GeneralError>
				+load(bool reload) : std::optional<IRacingSDK::GeneralError>
				+findFile(const std::shared_ptr<LapTrajectory>& dataFile) : std::optional<fs::path>
				+findFile(const std::string& trackLayoutId) : std::optional<fs::path>
				+getData(const std::string& trackLayoutId) : std::shared_ptr<LapTrajectory>
				+get(const std::string& trackLayoutId) : std::shared_ptr<TrackMapFile>
				+cacheSize() : std::size_t
				+pendingTaskCount() : std::size_t
				-dataFileTaskQueueFn(const std::shared_ptr<TelemetryDataFile>& dataFile) : std::string
				+listTrackMaps() : std::vector<fs::path>
				+toFileList() : std::vector<std::shared_ptr<TrackMapFile>>
				-enqueueDataFiles(const std::vector<std::shared_ptr<TelemetryDataFile>>& changedDataFiles) : void
				+reset(bool skipPrepare) : void
				+setOptions(Options options) : void
			}

			enum ServiceState {
				Created
				Destroyed
				Destroying
				Error
				Initialized
				Initializing
				Running
				Starting
			}

			class IRacingIPCServer::Client {
				+Client(const IPC::NamedPipeServer::ConnectionPtr& connection)
				+id : IPC::NamedPipeServer::ConnectionId
				+getConnection() : IPC::NamedPipeServer::ConnectionPtr
				+connectionRef : IPC::NamedPipeServer::ConnectionWeakPtr
			}

			class IRacingIPCServer::Options {
			}

			class LapTrajectoryTool::CreateOptions {
			}

			class RPCServerService::Options {
			}

			class RPCServerService::anon_struct_1 {
			}

			class ServiceManager::anon_struct_1 {
			}

			class SessionManagerService::anon_struct_1 {
			}

			class TelemetryDataService::Options {
			}

			class TelemetryDataService::anon_struct_1 {
			}

			class TelemetryFileHandler::GetLapDataContext {
			}

			class TelemetryFileHandler::LapPositionCoordinate {
				+LapPositionCoordinate(tuple<int, double, float, float, double, double, float> values)
				+altitude() : auto&
				+completeMeters() : auto&
				+completePercent() : auto&
				+lap() : auto&
				+lapTime() : auto&
				+latitude() : auto&
				+longitude() : auto&
				+setValue(tuple<int, double, float, float, double, double, float> values) : void
			}

			class TelemetryFileHandler::ProcessorOutput {
				+handler : TelemetryFileHandler*
			}

			class TrackMapService::Options {
			}

			class TrackMapService::anon_struct_1 {
			}

			class TrackMapService::anon_struct_2 {
			}

			namespace Pipelines {
				abstract class PipelineExecutor <template<typename ... Data>> {
					+PipelineExecutor(PipelineType type)
					+~PipelineExecutor()
					+type() : PipelineType {query}
					-type_ : const PipelineType
					+{abstract} execute(PipelineAttemptEditor attempt, const std::shared_ptr<ServiceContainer>& serviceContainer, Data ...) : std::optional<IRacingSDK::GeneralError>
				}

				class PipelineExecutorRegistry <template<PipelineType Type, typename Data>> {
					#PipelineExecutorRegistry(IRacingSDK::Utils::Singleton<PipelineExecutorRegistry<Type, Data>>::token)
					# : friend IRacingSDK::Utils::Singleton<PipelineExecutorRegistry<Type, Data>>
					+build() : std::shared_ptr<PipelineExecutor<Data>>
					+setFactory(const PipelineExecutorFactory<Data>& factory) : void
				}

				class TrackMapPipelineExecutor {
					+TrackMapPipelineExecutor()
					+~TrackMapPipelineExecutor()
					+execute(PipelineAttemptEditor& attempt, const std::shared_ptr<ServiceContainer>& serviceContainer, std::shared_ptr<TelemetryDataFile> data) : std::optional<IRacingSDK::GeneralError>
					+{static} Factory() : std::shared_ptr<TrackMapPipelineExecutor>
				}

				class PipelineExecutor::PipelineAttemptEditor {
					+PipelineAttemptEditor(Pipeline* pipeline, Pipeline::Attempt* attempt)
					+pipeline : Pipeline*
					+attempt : Pipeline::Attempt*
					+log(Logging::LevelType level, const std::string& message) : void
					+log(Logging::LevelType level, fmt::format_string<Args ...> fmt, Args&& ... args) : void
					+setStatus(PipelineStatus newStatus) : void
				}
			}
		}

		namespace Screen {
			class ScreenOverlayFrameRenderConfig {
			}
		}

		namespace SHM {
			class ConsumerPattern {
				+ConsumerPattern()
				+ConsumerPattern(std::underlying_type_t<ConsumerKind>( consumerKindMask ))
				+ConsumerPattern(ConsumerKind kind)
				+matches(ConsumerKind) : bool {query}
				+getRawMaskForDebugging() : std::underlying_type_t<ConsumerKind> {query}
			}

			class IPCClientTexture {
				#IPCClientTexture(const PixelSize &, uint8_t swapchainIndex)
				+~IPCClientTexture()
				+getDimensions() : PixelSize {query}
				-dimensions_ : const PixelSize
				-swapchainIndex_ : const uint8_t
				+getSwapchainIndex() : uint8_t {query}
			}

			abstract class IPCTextureCopier {
				+~IPCTextureCopier()
				+{abstract} copy(HANDLE sourceTexture, IPCClientTexture* destinationTexture, HANDLE fence, uint64_t fenceValueIn) : void
			}

			abstract class SHMCachedReader {
				+SHMCachedReader(IPCTextureCopier*, ConsumerKind)
				+~SHMCachedReader()
				+maybeGet() : Snapshot
				+maybeGetMetadata() : Snapshot
				-cache_ : std::deque<Snapshot>
				#{abstract} createIPCClientTexture(const PixelSize &, uint8_t swapchainIndex) : std::shared_ptr<IPCClientTexture>
				-getIPCClientTexture(const PixelSize &, uint8_t swapchainIndex) : std::shared_ptr<IPCClientTexture>
				-clientTextures_ : std::vector<std::shared_ptr<IPCClientTexture>>
				#initializeCache(uint64_t gpuAdapterId, uint8_t swapchainLength) : void
				#{abstract} releaseIPCHandles() : void
				-updateSession() : void
			}

			class SHMReader {
				+SHMReader()
				+operatorbool() {query}
				+~SHMReader()
				#maybeGetUncached(ConsumerKind) : Snapshot
				#maybeGetUncached(uint64_t gpuAdapterId, IPCTextureCopier* copier, const std::shared_ptr<IPCClientTexture>& dest, ConsumerKind) : Snapshot {query}
				+getRenderCacheKey(ConsumerKind kind) : size_t {query}
				#p : std::shared_ptr<Impl>
				+getFrameCountForMetricsOnly() : uint64_t {query}
				+getSessionId() : uint64_t {query}
			}

			class Snapshot {
				+Snapshot(nullptr_t)
				+Snapshot(incorrect_kind_t)
				+Snapshot(incorrect_gpu_t)
				+Snapshot(FrameMetadata*, IPCTextureCopier* copier, IPCHandles* source, const std::shared_ptr<IPCClientTexture>& dest)
				+Snapshot(FrameMetadata*)
				+~Snapshot()
				+getConfig() : SHMConfig {query}
				+getOverlayFrameConfig(uint8_t layerIndex) : SHMOverlayFrameConfig* {query}
				-state_ : State
				+getTexture() : T* {query}
				+hasMetadata() : bool {query}
				+hasTexture() : bool {query}
				+getState() : int {query}
				+getRenderCacheKey() : size_t {query}
				-metadata_ : std::shared_ptr<FrameMetadata>
				-ipcTexture_ : std::shared_ptr<IPCClientTexture>
				+getSequenceNumberForDebuggingOnly() : uint64_t {query}
				+getSessionID() : uint64_t {query}
				+getOverlayCount() : uint8_t {query}
			}

			class Writer {
				+Writer(uint64_t gpuAdapterId)
				+operatorbool() {query}
				+~Writer()
				+beginFrame() : NextFrameInfo
				+try_lock() : bool
				-impl_ : std::shared_ptr<Impl>
				+detach() : void
				+lock() : void
				+submitEmptyFrame() : void
				+submitFrame(const SHMConfig& config, const std::vector<SHMOverlayFrameConfig>& overlayFrameConfigs, HANDLE texture, HANDLE fence) : void
				+unlock() : void
			}

			enum ConsumerKind {
				NonVRD3D11
				OculusD3D11
				OculusD3D12
				OpenXR
				SteamVR
				Viewer
			}

			enum SHMHeaderFlags {
				FEEDER_ATTACHED
			}

			enum Snapshot::State {
				Empty
				IncorrectGPU
				IncorrectKind
				ValidWithTexture
				ValidWithoutTexture
			}

			class FrameMetadata {
				+config : SHMConfig
				+overlayFrameConfigs : SHMOverlayFrameConfig
				+haveOverlayProducer() : bool {query}
				+getRenderCacheKey() : std::size_t {query}
				+frameNumber : uint64_t
				+magic : uint64_t
				+sessionId : uint64_t
				+overlayFrameCount : uint8_t
			}

			class IPCHandles {
				+IPCHandles(HANDLE feederProcess, const FrameMetadata& frame)
				+foreignFenceHandle : const HANDLE
				+foreignTextureHandle : const HANDLE
				+fenceHandle : winrt::handle
				+textureHandle : winrt::handle
			}

			class LayerSprite {
				+destRect : PixelRect
				+sourceRect : PixelRect
			}

			class SHMConfig {
			}

			class SHMOverlayFrameConfig {
			}

			class Snapshot::incorrect_gpu_t {
			}

			class Snapshot::incorrect_kind_t {
			}

			class Writer::NextFrameInfo {
			}

			namespace DX11 {
				class SHMDX11CachedReader {
					+SHMDX11CachedReader(ConsumerKind)
					+~SHMDX11CachedReader()
					#copyFence_ : FenceAndValue
					#getIPCFence(HANDLE) : FenceAndValue*
					#getIPCTexture(HANDLE) : ID3D11Texture2D*
					#createIPCClientTexture(const PixelSize &, uint8_t swapchainIndex) : std::shared_ptr<SHM::IPCClientTexture>
					#ipcFences_ : std::unordered_map<HANDLE, FenceAndValue>
					#ipcTextures_ : std::unordered_map<HANDLE, winrt::com_ptr<ID3D11Texture2D>>
					#deviceLUID_ : uint64_t
					#copy(HANDLE sourceTexture, IPCClientTexture* destinationTexture, HANDLE fence, uint64_t fenceValueIn) : void
					+initializeCache(ID3D11Device*, uint8_t swapchainLength) : void
					#releaseIPCHandles() : void
					#waitForPendingCopies() : void
					#device_ : winrt::com_ptr<ID3D11Device5>
					#deviceContext_ : winrt::com_ptr<ID3D11DeviceContext4>
				}

				class Texture {
					+Texture(const PixelSize &, uint8_t swapchainIndex, const winrt::com_ptr<ID3D11Device5> &, const winrt::com_ptr<ID3D11DeviceContext4> &)
					+~Texture()
					+getD3D11ShaderResourceView() : ID3D11ShaderResourceView*
					+getD3D11Texture() : ID3D11Texture2D* {query}
					+copyFrom(ID3D11Texture2D* texture, ID3D11Fence* fenceIn, uint64_t fenceInValue, ID3D11Fence* fenceOut, uint64_t fenceOutValue) : void
					-device_ : winrt::com_ptr<ID3D11Device5>
					-context_ : winrt::com_ptr<ID3D11DeviceContext4>
					-cacheShaderResourceView_ : winrt::com_ptr<ID3D11ShaderResourceView>
					-cacheTexture_ : winrt::com_ptr<ID3D11Texture2D>
				}

				class SHMDX11CachedReader::FenceAndValue {
					+operatorbool() {query}
					+fence_ : winrt::com_ptr<ID3D11Fence>
				}
			}
		}

		namespace Logging {
			class LoggingManager {
				#LoggingManager(token)
				+getCategory(const std::string& name) : Logger
				+getConsoleLogger() : Logger
			}

			enum LogCategoryDefault {
				Global
				IRSDK
				Service
			}
		}

		namespace IPC {
			class DynamicBuffer {
				+DynamicBuffer(typename initialSize)
				#getStorage() : Storage&
				#getStorage() : Storage& {query}
				+resize(typename newSize) : bool
				-resizeInternal(typename newSize) : bool
				+clear() : void
				+reset() : void
			}

			class FixedBuffer <template<std::size_t N, typename T=BYTE>> {
				+FixedBuffer()
				+clone() : NamedPipeBuffer<std::array<T , N>>
				#getStorage() : Storage&
				#getStorage() : Storage& {query}
				+clear() : void
			}

			abstract class NamedPipeBuffer <template<typename Storage, typename=std::enable_if<is_container<Storage>& & std::is_scalar_v<typename Storage::value_type>>, typename=std::void_t<typename Storage::size_type>>> {
				+NamedPipeBuffer()
				+~NamedPipeBuffer()
				+availableToRead() : SizeType
				+availableToWrite() : SizeType
				+read(typename dst, typename len) : SizeType
				+readPosition() : SizeType
				+size() : SizeType
				+write(typename src, typename len) : SizeType
				+writePosition() : SizeType
				#{abstract} getStorage() : Storage&
				#{abstract} getStorage() : Storage& {query}
				+data() : ValueType*
				+data() : ValueType* {query}
				+readData() : ValueType*
				+writeData() : ValueType*
				+resize(typename newSize) : bool
				+reset() : void
				+setReadPosition(typename newReadPosition) : void
				+setWritePosition(typename newWritePosition) : void
			}

			class NamedPipeConnection {
				+NamedPipeConnection(Private, NamedPipeServer* server, HANDLE pipeHandle, std::size_t packetSize)
				+~NamedPipeConnection()
				+{static} CreateEvent() : HANDLE
				+pipeHandle() : HANDLE
				-pipeHandle_ : HANDLE
				+readOverlapped() : LPOVERLAPPED
				+writeOverlapped() : LPOVERLAPPED
				-messageFactory_ : MessageFactory
				+connectIO() : NamedPipeIO&
				+readIO() : NamedPipeIO&
				+writeIO() : NamedPipeIO&
				-server_ : NamedPipeServer*
				-messagePool_ : ObjectPool<NamedPipeMessage>
				+isConnected() : bool
				+isReadPending() : bool
				+setConnected(bool connected) : bool
				-packetSize_ : const std::size_t
				+connect() : std::expected<bool , std::exception>
				#onRead(std::size_t bytesRead) : std::expected<bool , std::exception>
				#onWrite(std::size_t bytesWritten) : std::expected<bool , std::exception>
				+startRead() : std::expected<bool , std::exception>
				+startWrite() : std::expected<bool , std::exception>
				+writeMessage(std::uint32_t id, std::uint32_t sourceId, const DynamicByteBuffer::ValueType* data, std::uint32_t size) : std::expected<bool , std::exception>
				+{static} Create(NamedPipeServer* server, HANDLE pipeHandle, std::size_t packetSize) : std::shared_ptr<NamedPipeConnection>
				+packetSize() : std::size_t {query}
				+id() : std::uint32_t {query}
				+allIO() : std::vector<NamedPipeIO*>
				+pendingEvents() : std::vector<NamedPipePendingEvent>
				+destroy() : void
			}

			class NamedPipeMessage {
				+NamedPipeMessage(const std::uint32_t& connectionId, std::size_t packetSize)
				+data() : DynamicByteBuffer::ValueType*
				+data() : DynamicByteBuffer::ValueType* {query}
				+getNextReadPacket() : MessageDataPacket
				+getNextWritePacket() : MessageDataPacket
				+reset() : NamedPipeMessage*
				+setError(const std::string& msg) : NamedPipeMessage*
				+header() : NamedPipeMessageHeader*
				+header() : NamedPipeMessageHeader* {query}
				#resetHeader() : NamedPipeMessageHeader*
				+allDataRead() : bool
				+hasError() : bool
				+isHeaderProcessed() : bool
				+isHeaderWritten() : bool
				-packetSize_ : const std::size_t
				-connectionId_ : const std::uint32_t
				+onRead(std::size_t bytesRead) : std::expected<bool , std::exception>
				+onWrite(std::size_t bytesWritten) : std::expected<bool , std::exception>
				+processHeader() : std::expected<bool , std::exception>
				+setData(const DynamicByteBuffer::ValueType* data, DynamicByteBuffer::SizeType length) : std::expected<bool , std::exception>
				+setHeader(const NamedPipeMessageHeader& newHeader) : std::expected<bool , std::exception>
				+error() : std::optional<std::exception> {query}
				+packetSize() : std::size_t {query}
				+size() : std::size_t
				+connectionId() : std::uint32_t {query}
				+id() : std::uint32_t
				+sourceId() : std::uint32_t
				+setHeaderWritten() : void
			}

			class NamedPipeServer {
				+NamedPipeServer(Private, const std::string& pipeName, function<void ( std::size_t size, const NamedPipeMessageDataType data, const NamedPipeMessageHeader* header, std::shared_ptr<NamedPipeConnection>connection, std::shared_ptr<NamedPipeServer>server )> messageHandler, const std::optional<NamedPipeServerOptions>& overrideOptions)
				+~NamedPipeServer()
				+events : <anon-struct-1>
				+hasAvailableConnection() : bool
				+isRunning() : bool
				+shouldCreateConnection() : bool
				+start(bool wait) : bool
				-options_ : const NamedPipeServerOptions
				-pipePath_ : const std::string
				-messageHandler_ : function<void ( std::size_t size, const NamedPipeMessageDataType data, const NamedPipeMessageHeader* header, std::shared_ptr<NamedPipeConnection>connection, std::shared_ptr<NamedPipeServer>server )>
				+writeMessage(std::uint32_t connectionId, std::uint32_t id, std::uint32_t sourceId, const DynamicByteBuffer::ValueType* data, std::uint32_t size) : std::expected<bool , std::exception>
				-createNewConnection() : std::expected<std::shared_ptr<NamedPipeConnection>, std::exception>
				-nextEmitMessage() : std::optional<MessagePtr>
				+getConnection(std::uint32_t connectionId) : std::shared_ptr<NamedPipeConnection>
				+{static} Create(const std::string& pipeName, function<void ( std::size_t size, const NamedPipeMessageDataType data, const NamedPipeMessageHeader* header, std::shared_ptr<NamedPipeConnection>connection, std::shared_ptr<NamedPipeServer>server )> messageHandler, const std::optional<NamedPipeServerOptions>& overrideOptions) : std::shared_ptr<NamedPipeServer>
				+packetSize() : std::size_t {query}
				+pipePath() : std::string {query}
				+closeConnection(std::uint32_t connectionId) : void
				+closeConnection(shared_ptr<NamedPipeConnection> connection) : void
				#emitMessage(const std::shared_ptr<NamedPipeMessage>& message) : void
				-emitRunnable() : void
				-ioRunnable() : void
				+ioThreadNotify() : void
				+stop() : void
				+waitUntilStopped() : void
			}

			abstract class NamedPipeServerRoute {
				+NamedPipeServerRoute(const std::string& matchExpression)
				+~NamedPipeServerRoute()
				+accepts(const std::string& path) : bool
				+{abstract} execute(shared_ptr<Models::RPC::Envelope> messageIn, shared_ptr<Models::RPC::Envelope> messageOut) : std::expected<Envelope , IRacingSDK::GeneralError>
				-matcher_ : std::regex
				-matchExpression_ : std::string
			}

			class NamedPipeServerTypedRoute <template<typename RequestType, typename ResponseType>> {
				+NamedPipeServerTypedRoute(function<std::expected<std::shared_ptr<ResponseType>, IRacingSDK::GeneralError>( const std::shared_ptr<RequestType>&, const std::shared_ptr<RPC::Envelope>& )> executor, const std::string& matchExpression)
				-executor_ : function<std::expected<std::shared_ptr<ResponseType>, IRacingSDK::GeneralError>( const std::shared_ptr<RequestType>&, const std::shared_ptr<RPC::Envelope>& )>
				+execute(shared_ptr<Models::RPC::Envelope> messageIn, shared_ptr<Models::RPC::Envelope> messageOut) : std::expected<Envelope , IRacingSDK::GeneralError>
				+{static} Create(function<std::expected<std::shared_ptr<ResponseType>, IRacingSDK::GeneralError>( const std::shared_ptr<RequestType>&, const std::shared_ptr<RPC::Envelope>& )> executor, const std::string& matchExpression) : std::shared_ptr<NamedPipeServerTypedRoute>
			}

			class ObjectPool <template<typename T>> {
				+ObjectPool(function<T* ( )> factory)
				+~ObjectPool()
				+factory_(std::move ( factory )) : ) :
				+acquire() : PointerType
				-factory_ : function<T* ( )>
				-mutex_ : std::mutex
				-availableObjects_ : std::stack<std::unique_ptr<T>>
			}

			enum NamedPipeErrorCode {
				Connection
				Event
				Read
				Unknown
				Write
			}

			enum NamedPipeIO::Role {
				Connect
				Read
				Write
			}

			class MessageFactory {
				+MessageFactory(NamedPipeServer* server, std::uint32_t connectionId)
				+operator()() : NamedPipeMessage*
				+server : NamedPipeServer*
				+connectionId : std::uint32_t
			}

			class NamedPipeBuffer::anon_struct_1 {
				+read : typename
				+write : typename
			}

			class NamedPipeConnection::Private {
				+Private()
			}

			class NamedPipeIO {
				+NamedPipeIO(std::uint32_t connectionId, Role role)
				+role : Role
				+toString() : std::string
				+id : std::uint32_t
			}

			class NamedPipeMessageHeader {
			}

			class NamedPipeServer::Private {
				+Private()
			}

			class NamedPipeServer::anon_struct_1 {
			}

			class NamedPipeServerOptions {
				+NamedPipeServerOptions(const std::optional<NamedPipeServerOptions>& overrideOptions)
			}

			class ObjectPool::Deleter {
				+Deleter(ObjectPool& pool)
				-pool_ : ObjectPool&
				+operator()(T* ptr) : void {query}
			}
		}

		namespace Graphics {
			class D2DResources {
				#D2DResources(D3D11Resources*)
				+~D2DResources()
				+popD2DDraw() : HRESULT
				-locks_ : std::unique_ptr<Locks>
				+pushD2DDraw() : void
				#d2dDevice_ : winrt::com_ptr<ID2D1Device>
				+getD2DDevice() : winrt::com_ptr<ID2D1Device>&
				#d2dDeviceContext_ : winrt::com_ptr<ID2D1DeviceContext5>
				+getD2DDeviceContext() : winrt::com_ptr<ID2D1DeviceContext5>&
				#d2dFactory_ : winrt::com_ptr<ID2D1Factory1>
				+getD2DFactory() : winrt::com_ptr<ID2D1Factory1>&
				#directWriteFactory_ : winrt::com_ptr<IDWriteFactory>
				+getDirectWriteFactory() : winrt::com_ptr<IDWriteFactory>&
			}

			class D3D11Resources {
				#D3D11Resources()
				+~D3D11Resources()
				+try_lock() : bool
				-locks_ : std::unique_ptr<Locks>
				#dxgiAdapterLUID_ : uint64_t
				+getDXGIAdapterLUID() : uint64_t
				+lock() : void
				+unlock() : void
				#dxDevice_ : winrt::com_ptr<ID3D11Device5>
				+getDXDevice() : winrt::com_ptr<ID3D11Device5>&
				#dxImmediateContext_ : winrt::com_ptr<ID3D11DeviceContext4>
				+getDXImmediateContext() : winrt::com_ptr<ID3D11DeviceContext4>&
				#dxgiAdapter_ : winrt::com_ptr<IDXGIAdapter4>
				+getDXGIAdapter() : winrt::com_ptr<IDXGIAdapter4>&
				#dxgiDevice_ : winrt::com_ptr<IDXGIDevice2>
				+getDXGIDevice() : winrt::com_ptr<IDXGIDevice2>&
				#dxgiFactory_ : winrt::com_ptr<IDXGIFactory6>
				+getDXGIFactory() : winrt::com_ptr<IDXGIFactory6>&
			}

			class DXResources {
				+DXResources()
				#s2sBackBufferDeviceContext_ : Microsoft::WRL::ComPtr<ID2D1DeviceContext5>
				#spriteBatch_ : std::unique_ptr<SpriteBatch>
				#blackBrush_ : winrt::com_ptr<ID2D1SolidColorBrush>
				#cursorInnerBrush_ : winrt::com_ptr<ID2D1SolidColorBrush>
				#cursorOuterBrush_ : winrt::com_ptr<ID2D1SolidColorBrush>
				#eraserBrush_ : winrt::com_ptr<ID2D1SolidColorBrush>
				#highlightBrush_ : winrt::com_ptr<ID2D1SolidColorBrush>
				#whiteBrush_ : winrt::com_ptr<ID2D1SolidColorBrush>
				+getBlackBrush() : winrt::com_ptr<ID2D1SolidColorBrush>&
				+getCursorInnerBrush() : winrt::com_ptr<ID2D1SolidColorBrush>&
				+getCursorOuterBrush() : winrt::com_ptr<ID2D1SolidColorBrush>&
				+getEraserBrush() : winrt::com_ptr<ID2D1SolidColorBrush>&
				+getHighlightBrush() : winrt::com_ptr<ID2D1SolidColorBrush>&
				+getWhiteBrush() : winrt::com_ptr<ID2D1SolidColorBrush>&
			}

			class DXWindowResources {
				+DXWindowResources(HWND windowHandle, const std::shared_ptr<DXResources>& dxr)
				-windowHandle_ : HWND
				+currentWindowSize() : Size<UINT>
				+resourceWindowSize() : Size<UINT>
				+areResourcesValid() : bool
				+prepare() : bool
				-dxr_ : std::shared_ptr<DXResources>
				+renderTarget() : std::shared_ptr<RenderTarget>
				+reset() : void
				+backBuffer() : winrt::com_ptr<ID3D11Texture2D>&
				-dComp_ : winrt::com_ptr<IDCompositionDevice>
				+dComp() : winrt::com_ptr<IDCompositionDevice>&
				-dCompTarget_ : winrt::com_ptr<IDCompositionTarget>
				+dCompTarget() : winrt::com_ptr<IDCompositionTarget>&
				-dCompVisual_ : winrt::com_ptr<IDCompositionVisual>
				+dCompVisual() : winrt::com_ptr<IDCompositionVisual>&
				+swapChain() : winrt::com_ptr<IDXGISwapChain1>&
			}

			class IPCOverlayCanvasRenderer <template<ImageFormatChannels FormatChannels>> {
				+IPCOverlayCanvasRenderer(Producer* producer, const std::shared_ptr<DXResources>& dxr)
				+~IPCOverlayCanvasRenderer()
				+getOrCreateOverlayImageDataBuffer(std::uint8_t idx, std::shared_ptr<IPCOverlayFrameData<FormatChannels>> overlayData) : BufferPtr
				-consumerThread_ : IRacingSDK::Utils::FnIndefiniteThread
				-producer_ : Producer*
				+getTextureResources(uint8_t textureIndex, const PixelSize& size) : TextureResources*
				-isRendering_ : std::atomic_flag
				-dxr_ : std::shared_ptr<DXResources>
				+{static} Create(Producer* producer) : std::shared_ptr<IPCOverlayCanvasRenderer>
				-writer_ : std::shared_ptr<SHM::Writer>
				-consumerRunnable(IRacingSDK::Utils::FnIndefiniteThread* t) : void
				+destroy() : void
				+initializeCanvas(const PixelSize& size) : void
				+render() : void
				+submitFrame(const std::vector<SHM::SHMOverlayFrameConfig>& shmOverlayFrameConfigs) : void
			}

			class IPCOverlayFrameData <template<ImageFormatChannels FormatChannels>> {
				+IPCOverlayFrameData(const PixelSize& imageSize, const ScreenRect& screenRect, const VR::VRNativeLayout& vrLayout)
				+getImageSize() : PixelSize {query}
				+imageSize() : PixelSize
				+screenRect() : ScreenRect
				+vrLayout() : VR::VRNativeLayout
				+update(const PixelSize& imageSize, const ScreenRect& screenRect, const VR::VRNativeLayout& vrLayout) : bool
				-imageData_ : const std::shared_ptr<ImageDataBufferContainer<FormatChannels>>
				+imageData() : std::shared_ptr<ImageDataBufferContainer<FormatChannels>>
				+getImageDataSize() : std::uint32_t {query}
				+getImageDataStride() : std::uint32_t {query}
			}

			class ImageDataBuffer <template<ImageFormatChannels FormatChannels>> {
				+ImageDataBuffer(const std::uint32_t& width, const std::uint32_t& height)
				+~ImageDataBuffer()
				+data() : Byte*
				+hasData() : bool {query}
				+hasNewData() : bool {query}
				+hasOldData() : bool {query}
				+isDestroyed() : bool {query}
				+isEmpty() : bool {query}
				+isValid() : bool
				+resize(const std::uint32_t& width, const std::uint32_t& height) : bool
				+tryLock() : bool
				+try_lock() : bool
				+bpp : const std::uint32_t
				+setStatus(Status newStatus) : int
				+status() : int {query}
				+{static} BPP : static constexpr auto
				-height_ : std::atomic_uint32_t
				-width_ : std::atomic_uint32_t
				+consume(function<std::uint32_t ( const Byte* data, std::uint32_t size, ImageDataBuffer* imageDataBuffer )> fn) : std::expected<std::uint32_t , IRacingSDK::GeneralError>
				+produce(function<std::uint32_t ( Byte* data, std::uint32_t size, ImageDataBuffer* imageDataBuffer )> fn) : std::expected<std::uint32_t , IRacingSDK::GeneralError>
				+produce(uint8_t src, std::uint32_t size) : std::expected<std::uint32_t , IRacingSDK::GeneralError>
				+produce(vector<Byte> buf) : std::expected<std::uint32_t , IRacingSDK::GeneralError>
				+height() : std::uint32_t
				+size() : std::uint32_t {query}
				+stride() : std::uint32_t {query}
				+width() : std::uint32_t
				+frameIndex() : uint32_t
				+setFrameIndex(std::uint32_t newFrameIndex) : uint32_t
				+destroy() : void
				+lock() : void
				+reset() : void
				+setEmpty() : void
				+unlock() : void
			}

			class ImageDataBufferContainer <template<ImageFormatChannels FormatChannels>> {
				+ImageDataBufferContainer(const std::uint32_t& width, const std::uint32_t& height)
				+newBuffer() : BufferPtr
				+getImageSize() : PixelSize {query}
				+consume(shared_ptr<Buffer> targetBuffer) : bool
				+resize(const std::uint32_t& width, const std::uint32_t& height, bool force) : bool
				+bpp : const std::uint32_t
				+{static} BPP : static constexpr auto
				+produce(typename ImageDataBuffer<FormatChannels>::Byte data, std::uint32_t len) : std::expected<std::uint32_t , IRacingSDK::GeneralError>
				+getImageDataSize() : std::uint32_t {query}
				+getImageDataStride() : std::uint32_t {query}
				+height() : std::uint32_t
				-height_ : std::uint32_t
				+width() : std::uint32_t
				-width_ : std::uint32_t
				+destroy() : void
			}

			class Opacity {
				+Opacity(float opacity)
				+XMVECTORF32() {query}
				-color_ : DirectX::XMVECTORF32
			}

			class RenderTarget {
				#RenderTarget(const std::shared_ptr<DXResources>& dxr, const winrt::com_ptr<ID3D11Texture2D>& texture)
				+~RenderTarget()
				+d2d() : D2D
				+d3d() : D3D
				-dimensions_ : PixelSize
				+getDimensions() : PixelSize {query}
				-dxr_ : std::shared_ptr<DXResources>
				+{static} Create(const std::shared_ptr<DXResources>& dxr, const winrt::com_ptr<ID3D11Texture2D>& texture) : std::shared_ptr<RenderTarget>
				+{static} Create(const std::shared_ptr<DXResources>& dxr, nullptr_t texture) : std::shared_ptr<RenderTarget>
				+setD3DTexture(const winrt::com_ptr<ID3D11Texture2D> &) : void
				-d2dBitmap_ : winrt::com_ptr<ID2D1Bitmap1>
				-d3dRenderTargetView_ : winrt::com_ptr<ID3D11RenderTargetView>
				-d3dTexture_ : winrt::com_ptr<ID3D11Texture2D>
				+d3dTexture() : winrt::com_ptr<ID3D11Texture2D>&
			}

			class RenderTarget::D2D {
				+D2D(const std::shared_ptr<RenderTarget> &)
				+operatorID2D1DeviceContext*() {query}
				+~D2D()
				+operator->() : ID2D1DeviceContext* {query}
				-parent_ : std::shared_ptr<RenderTarget>
				-acquire() : void
				+reacquire() : void
				+release() : void
			}

			class RenderTarget::D3D {
				+D3D(const std::shared_ptr<RenderTarget> &)
				+~D3D()
				+rtv() : ID3D11RenderTargetView* {query}
				+texture() : ID3D11Texture2D* {query}
				-parent_ : std::shared_ptr<RenderTarget>
			}

			abstract class Renderable <template<typename T>> {
				+Renderable(const std::shared_ptr<DXResources>& resources)
				+~Renderable()
				#resources_ : std::shared_ptr<DXResources>
				+resources() : std::shared_ptr<DXResources>&
				+{abstract} render(const std::shared_ptr<RenderTarget>& target, const T& data) : void
			}

			class SavedState {
				+SavedState(const winrt::com_ptr<ID3D11DeviceContext> &)
				+SavedState(ID3D11DeviceContext*)
				+~SavedState()
			}

			class SpriteBatch {
				+SpriteBatch(ID3D11Device*)
				+~SpriteBatch()
				-dxtkSpriteBatch_ : std::unique_ptr<DirectX::DX11::SpriteBatch>
				+begin(ID3D11RenderTargetView*, const PixelSize& rtvSize, std::function<void __cdecl ( )> setCustomShaders) : void
				+clear(DirectX::XMVECTORF32 color) : void
				+draw(ID3D11ShaderResourceView* source, const PixelRect& sourceRect, const PixelRect& destRect, DirectX::XMVECTORF32 tint) : void
				+end() : void
				-device_ : winrt::com_ptr<ID3D11Device>
				-deviceContext_ : winrt::com_ptr<ID3D11DeviceContext>
			}

			class WriteReadBuffer {
				+WriteReadBuffer(const std::optional<Config>& options)
				+~WriteReadBuffer()
				+readBuffer() : Byte*
				+writeBuffer() : Byte*
				-config_ : Config
				+isValid() : bool
				+lockReadTry() : bool
				+lockWriteTry() : bool
				+onSwapRead(function<bool ( const Byte* buf, std::uint32_t size, const Config& config )> fn) : bool
				+read(function<bool ( const Byte* buf, std::uint32_t size, const Config& config )> fn) : bool
				+write(vector<Byte> buf, std::uint32_t size, bool skipSwap) : bool
				+write(uint8_t buf, std::uint32_t size, bool skipSwap) : bool
				+{static} BytesPerPixelRGB : static constexpr std::uint32_t
				+{static} BytesPerPixelRGBA : static constexpr std::uint32_t
				+readMutex() : std::recursive_mutex&
				+writeMutex() : std::recursive_mutex&
				+bufferSize() : std::uint32_t
				+readBufferSize() : std::uint32_t
				+writeBufferSize() : std::uint32_t
				+destroy() : void
				+lockRead() : void
				+lockWrite() : void
				+reconfigure(Config newConfig) : void
				-reset() : void
				+unlockRead() : void
				+unlockWrite() : void
			}

			enum GraphicsPlatform {
				D3D11
				D3D12
				Vulkan
			}

			enum ImageDataBuffer::Status {
				Destroyed
				Empty
				NewData
				OldData
			}

			enum ImageFormatChannels {
				BGRA
				RGB
				RGBA
			}

			enum RenderTarget::Mode {
				D2D
				D3D
				Unattached
			}

			abstract class DeviceListener {
				+~DeviceListener()
				+{abstract} onDeviceLost() : void
				+{abstract} onDeviceRestored() : void
			}

			class IPCOverlayCanvasRenderer::TextureResources {
				+textureSize : PixelSize
				+fence : winrt::com_ptr<ID3D11Fence>
				+renderTargetView : winrt::com_ptr<ID3D11RenderTargetView>
				+texture : winrt::com_ptr<ID3D11Texture2D>
				+fenceHandle : winrt::handle
				+textureHandle : winrt::handle
			}

			abstract class IPCOverlayFrameProducer <template<ImageFormatChannels FormatChannels>> {
				+~IPCOverlayFrameProducer()
				+{abstract} getOverlayData(std::size_t idx) : std::shared_ptr<IPCOverlayFrameData<FormatChannels>>
				+{abstract} getOverlayCount() : std::size_t
				+{abstract} onOverlayFrameData(function<void ( )> fn) : void
			}

			class WriteReadBuffer::Config {
				+Config(const std::uint32_t& width, const std::uint32_t& height, const std::uint32_t& bpp)
				+{static} Create(const std::uint32_t& width, const std::uint32_t& height, const std::uint32_t& bpp) : Config
				+isValid() : bool {query}
				+bufferSize() : std::uint32_t {query}
			}
		}

		namespace Geometry {
			class CoordinateToPixelConverter <template<typename PixelType=float>> {
				+CoordinateToPixelConverter(size_t zoomLevel)
				+pixelToCoordinate(PixelBase<PixelType> pixel) : Coordinate<>
				+coordinateToPixel(const Coordinate<>& coord) : Pixel
				+clampPixelValue(double value) : PixelType
				+zoomLevel() : ZoomLevel {query}
				-zoomLevel_ : size_t
				+{static} kConvertToInteger : static constexpr bool
			}

			enum MetricUnit {
				KM
				Kilometer
				M
				Meter
			}

			class Coordinate <template<typename T=double>> {
				+latitude : T
				+longitude : T
			}

			class PixelBase <template<typename T>> {
				+x : T
				+y : T
			}
		}

		namespace FileSystem {
			class FileWatcher {
				+FileWatcher(std::wstring path, UnderpinningRegex pattern, function<void ( const WatchEventData& file, WatchEvent eventType )> callback, bool autostart)
				+FileWatcher(std::wstring path, function<void ( const WatchEventData& file, WatchEvent eventType )> callback)
				+FileWatcher(const fs::path& path, UnderpinningRegex pattern, function<void ( const WatchEventData& file, WatchEvent eventType )> callback)
				+FileWatcher(const fs::path& path, function<void ( const WatchEventData& file, WatchEvent eventType )> callback)
				+FileWatcher(const FileWatcher& other)
				+~FileWatcher()
				-getFileAttributesX(const char* lpFileName, Args ... args) : DWORD
				-getFileAttributesX(const wchar_t* lpFileName, Args ... args) : DWORD
				+operator=(const FileWatcher& other) : FileWatcher&
				-createFileX(const char* lpFileName, Args ... args) : HANDLE
				-createFileX(const wchar_t* lpFileName, Args ... args) : HANDLE
				-getDirectoryHandle(const std::wstring& path) : HANDLE
				-pattern_ : UnderpinningRegex
				+isRunning() : bool
				-passFilter(const UnderpinningString& filePath) : bool
				-listenFilters_ : const DWORD
				-path_ : fs::path
				-callback_ : function<void ( const WatchEventData& file, WatchEvent eventType )>
				-callbackThread_ : std::thread
				-watchThread_ : std::thread
				-callbackInformation_ : std::vector<std::pair<WatchEventData, WatchEvent>>
				-filename_ : std::wstring
				-callbackThread() : void
				-monitorDirectory() : void
				+start() : void
				+stop() : void
			}

			enum WatchEvent {
				Added
				Modified
				Removed
				RenamedNew
				RenamedOld
			}

			class FileWatcher::PathParts {
				+PathParts(std::wstring directory, std::wstring filename)
			}

			class FileWatcher::WatchEventData {
				+path : fs::path
				+pathString : std::wstring
			}

			class IsWChar <template<typename StringType>> {
				+{static} value : static constexpr auto
			}

			class IsWCharwchar_t <template<>> {
				+{static} value : static constexpr auto
			}
		}

		namespace Common {
			class TaskQueue <template<class R, class ... Args>> {
				+TaskQueue(function<R ( Args ... )> fn, const std::optional<Options>& overrideOptions)
				+~TaskQueue()
				+enqueue(Args ... args) : FutureType
				+options() : Options {query}
				-options_ : Options
				+hasPendingTasks() : bool
				-fn_ : function<R ( Args ... )>
				+pendingTaskCount() : std::size_t
				+destroy() : void
				#runnable() : void
			}

			class TaskQueue::Options {
			}
		}

		namespace Chrono {
			class Timer {
				+Timer()
				+~Timer()
				+add(time_point<Clock> when, function<void ( TimerId )> handler, microseconds period) : TimerId
				+add(const std::chrono::duration<Rep, Period>& when, function<void ( TimerId )> handler, microseconds period) : TimerId
				+add(const uint64_t when, function<void ( TimerId )> handler, const uint64_t period) : TimerId
				-done_ : bool
				+remove(size_t id) : bool
				-cond_ : std::condition_variable
				-timeEvents_ : std::multiset<detail::TimeEvent>
				-mutex_ : std::mutex
				-freeIds_ : std::stack<TimerId>
				-worker_ : std::thread
				-events_ : std::vector<detail::Event>
				-run() : void
			}

			namespace detail {
				class Event {
					+Event()
					+Event(size_t id, time_point<Clock> start, microseconds period, Func&& handler)
					+Event(Event&& r)
					+operator=(Event&& ev) : Event&
					+valid : bool
					+handler : function<void ( TimerId )>
					+period : microseconds
					+id : size_t
					+start : time_point<Clock>
				}

				class TimeEvent {
					+ref : size_t
					+next : time_point<Clock>
				}
			}
		}
	}
}





/' Inheritance relationships '/

IRacingTools.Shared.UI.BaseWindow <|-- IRacingTools.Shared.UI.NormalWindow


IRacingTools.Shared.Graphics.D2DResources <|-- IRacingTools.Shared.Graphics.DXResources


IRacingTools.Shared.Graphics.D3D11Resources <|-- IRacingTools.Shared.Graphics.DXResources


IRacingTools.Shared.SHM.IPCClientTexture <|-- IRacingTools.Shared.SHM.DX11.Texture


IRacingTools.Shared.UI.IViewerWindowRenderer <|-- IRacingTools.Shared.UI.ViewerWindowD3D11Renderer


IRacingTools.Shared.IPC.NamedPipeBuffer <|-- IRacingTools.Shared.IPC.DynamicBuffer


IRacingTools.Shared.IPC.NamedPipeBuffer <|-- IRacingTools.Shared.IPC.FixedBuffer


IRacingTools.Shared.IPC.NamedPipeServerRoute <|-- IRacingTools.Shared.IPC.NamedPipeServerTypedRoute


IRacingTools.Shared.UI.NormalWindow <|-- IRacingTools.Shared.UI.ViewerWindow


IRacingTools.Shared.Services.Pipelines.PipelineExecutor <|-- IRacingTools.Shared.Services.Pipelines.TrackMapPipelineExecutor


IRacingTools.Shared.SHM.SHMReader <|-- IRacingTools.Shared.SHM.SHMCachedReader


IRacingTools.Shared.Services.Service <|-- IRacingTools.Shared.Services.RPCServerService


IRacingTools.Shared.Services.Service <|-- IRacingTools.Shared.Services.SessionManagerService


IRacingTools.Shared.Services.Service <|-- IRacingTools.Shared.Services.TelemetryDataService


IRacingTools.Shared.Services.Service <|-- IRacingTools.Shared.Services.TrackMapService


IRacingTools.Shared.Services.ServiceContainer <|-- IRacingTools.Shared.Services.ServiceManager


IRacingTools.Shared.SessionDataProvider <|-- IRacingTools.Shared.DiskSessionDataProvider


IRacingTools.Shared.SessionDataProvider <|-- IRacingTools.Shared.LiveSessionDataProvider


IRacingTools.Shared.UI.Window <|-- IRacingTools.Shared.UI.BaseWindow





/' Aggregation relationships '/

IRacingTools.Shared.Graphics.DXResources *-- IRacingTools.Shared.Graphics.SpriteBatch


IRacingTools.Shared.Graphics.DXWindowResources *-- IRacingTools.Shared.Graphics.DXResources


IRacingTools.Shared.FileSystem.FileWatcher "2" *-- IRacingTools.Shared.FileSystem.WatchEvent


IRacingTools.Shared.SHM.FrameMetadata *-- IRacingTools.Shared.SHM.SHMConfig


IRacingTools.Shared.SHM.FrameMetadata *-- IRacingTools.Shared.SHM.SHMOverlayFrameConfig


IRacingTools.Shared.Graphics.IPCOverlayCanvasRenderer *-- IRacingTools.Shared.Graphics.DXResources


IRacingTools.Shared.Graphics.IPCOverlayCanvasRenderer *-- IRacingTools.Shared.SHM.Writer


IRacingTools.Shared.Graphics.IPCOverlayFrameData *-- IRacingTools.Shared.Graphics.ImageDataBufferContainer


IRacingTools.Shared.Services.IRacingIPCServer::Client "2" *-- IRacingTools.Shared.IPC.NamedPipeServer


IRacingTools.Shared.IPC.MessageFactory o-- IRacingTools.Shared.IPC.NamedPipeServer


IRacingTools.Shared.IPC.NamedPipeConnection *-- IRacingTools.Shared.IPC.MessageFactory


IRacingTools.Shared.IPC.NamedPipeConnection *-- IRacingTools.Shared.IPC.NamedPipeMessage


IRacingTools.Shared.IPC.NamedPipeConnection o-- IRacingTools.Shared.IPC.NamedPipeServer


IRacingTools.Shared.IPC.NamedPipeConnection *-- IRacingTools.Shared.IPC.ObjectPool


IRacingTools.Shared.IPC.NamedPipeServer *-- IRacingTools.Shared.IPC.NamedPipeConnection


IRacingTools.Shared.IPC.NamedPipeServer o-- IRacingTools.Shared.IPC.NamedPipeMessageHeader


IRacingTools.Shared.IPC.NamedPipeServer *-- IRacingTools.Shared.IPC.NamedPipeServer


IRacingTools.Shared.IPC.NamedPipeServer *-- IRacingTools.Shared.IPC.NamedPipeServerOptions


IRacingTools.Shared.IPC.ObjectPool::Deleter *-- IRacingTools.Shared.IPC.ObjectPool


IRacingTools.Shared.Services.Pipelines.PipelineExecutorRegistry *-- IRacingTools.Shared.Services.Pipelines.PipelineExecutorRegistry


IRacingTools.Shared.Graphics.RenderTarget *-- IRacingTools.Shared.Graphics.DXResources


IRacingTools.Shared.Graphics.RenderTarget::D2D *-- IRacingTools.Shared.Graphics.RenderTarget


IRacingTools.Shared.Graphics.RenderTarget::D3D *-- IRacingTools.Shared.Graphics.RenderTarget


IRacingTools.Shared.Graphics.Renderable *-- IRacingTools.Shared.Graphics.DXResources


IRacingTools.Shared.SHM.SHMCachedReader *-- IRacingTools.Shared.SHM.IPCClientTexture


IRacingTools.Shared.SHM.SHMCachedReader *-- IRacingTools.Shared.SHM.Snapshot


IRacingTools.Shared.Services.Service *-- IRacingTools.Shared.Services.ServiceContainer


IRacingTools.Shared.SHM.Snapshot *-- IRacingTools.Shared.SHM.FrameMetadata


IRacingTools.Shared.SHM.Snapshot *-- IRacingTools.Shared.SHM.IPCClientTexture


IRacingTools.Shared.Graphics.SpriteBatch *-- IRacingTools.Shared.Graphics.SpriteBatch


IRacingTools.Shared.Services.TelemetryFileHandler::ProcessorOutput o-- IRacingTools.Shared.Services.TelemetryFileHandler


IRacingTools.Shared.Chrono.Timer *-- IRacingTools.Shared.Chrono.detail.Event


IRacingTools.Shared.Chrono.Timer *-- IRacingTools.Shared.Chrono.detail.TimeEvent


IRacingTools.Shared.VR.VROverlayFrameRenderConfig *-- IRacingTools.Shared.VR.VRNativeLayout


IRacingTools.Shared.UI.ViewerWindowD3D11Renderer *-- IRacingTools.Shared.Graphics.SpriteBatch






/' Nested objects '/

IRacingTools.Shared.UI.BaseWindow +-- IRacingTools.Shared.UI.BaseWindow::anon_struct_1


IRacingTools.Shared.DiskSessionDataProvider +-- IRacingTools.Shared.DiskSessionDataProvider::Options


IRacingTools.Shared.FileSystem.FileWatcher +-- IRacingTools.Shared.FileSystem.FileWatcher::PathParts


IRacingTools.Shared.FileSystem.FileWatcher +-- IRacingTools.Shared.FileSystem.FileWatcher::WatchEventData


IRacingTools.Shared.Graphics.IPCOverlayCanvasRenderer +-- IRacingTools.Shared.Graphics.IPCOverlayCanvasRenderer::TextureResources


IRacingTools.Shared.Services.IRacingIPCServer +-- IRacingTools.Shared.Services.IRacingIPCServer::Client


IRacingTools.Shared.Services.IRacingIPCServer +-- IRacingTools.Shared.Services.IRacingIPCServer::Options


IRacingTools.Shared.Graphics.ImageDataBuffer +-- IRacingTools.Shared.Graphics.ImageDataBuffer::Status


IRacingTools.Shared.Utils.JSONLinesMessageFileHandler +-- IRacingTools.Shared.Utils.JSONLinesMessageFileHandler::anon_struct_1


IRacingTools.Shared.Services.LapTrajectoryTool +-- IRacingTools.Shared.Services.LapTrajectoryTool::CreateOptions


IRacingTools.Shared.IPC.NamedPipeBuffer +-- IRacingTools.Shared.IPC.NamedPipeBuffer::anon_struct_1


IRacingTools.Shared.IPC.NamedPipeConnection +-- IRacingTools.Shared.IPC.NamedPipeConnection::Private


IRacingTools.Shared.IPC.NamedPipeIO +-- IRacingTools.Shared.IPC.NamedPipeIO::Role


IRacingTools.Shared.IPC.NamedPipeServer +-- IRacingTools.Shared.IPC.NamedPipeServer::Private


IRacingTools.Shared.IPC.NamedPipeServer +-- IRacingTools.Shared.IPC.NamedPipeServer::anon_struct_1


IRacingTools.Shared.IPC.ObjectPool +-- IRacingTools.Shared.IPC.ObjectPool::Deleter


IRacingTools.Shared.Services.Pipelines.PipelineExecutor +-- IRacingTools.Shared.Services.Pipelines.PipelineExecutor::PipelineAttemptEditor


IRacingTools.Shared.Services.RPCServerService +-- IRacingTools.Shared.Services.RPCServerService::Options


IRacingTools.Shared.Services.RPCServerService +-- IRacingTools.Shared.Services.RPCServerService::Route


IRacingTools.Shared.Services.RPCServerService +-- IRacingTools.Shared.Services.RPCServerService::TypedRoute


IRacingTools.Shared.Services.RPCServerService +-- IRacingTools.Shared.Services.RPCServerService::anon_struct_1


IRacingTools.Shared.Rect +-- IRacingTools.Shared.Rect::Origin


IRacingTools.Shared.Graphics.RenderTarget +-- IRacingTools.Shared.Graphics.RenderTarget::Mode


IRacingTools.Shared.SHM.DX11.SHMDX11CachedReader +-- IRacingTools.Shared.SHM.DX11.SHMDX11CachedReader::FenceAndValue


IRacingTools.Shared.Services.ServiceManager +-- IRacingTools.Shared.Services.ServiceManager::anon_struct_1


IRacingTools.Shared.Services.SessionManagerService +-- IRacingTools.Shared.Services.SessionManagerService::anon_struct_1


IRacingTools.Shared.SHM.Snapshot +-- IRacingTools.Shared.SHM.Snapshot::State


IRacingTools.Shared.SHM.Snapshot +-- IRacingTools.Shared.SHM.Snapshot::incorrect_gpu_t


IRacingTools.Shared.SHM.Snapshot +-- IRacingTools.Shared.SHM.Snapshot::incorrect_kind_t


IRacingTools.Shared.Common.TaskQueue +-- IRacingTools.Shared.Common.TaskQueue::Options


IRacingTools.Shared.Services.TelemetryDataService +-- IRacingTools.Shared.Services.TelemetryDataService::Options


IRacingTools.Shared.Services.TelemetryDataService +-- IRacingTools.Shared.Services.TelemetryDataService::anon_struct_1


IRacingTools.Shared.Services.TelemetryFileHandler +-- IRacingTools.Shared.Services.TelemetryFileHandler::GetLapDataContext


IRacingTools.Shared.Services.TelemetryFileHandler +-- IRacingTools.Shared.Services.TelemetryFileHandler::LapPositionCoordinate


IRacingTools.Shared.Services.TelemetryFileHandler +-- IRacingTools.Shared.Services.TelemetryFileHandler::ProcessorOutput


IRacingTools.Shared.Services.TrackMapService +-- IRacingTools.Shared.Services.TrackMapService::Options


IRacingTools.Shared.Services.TrackMapService +-- IRacingTools.Shared.Services.TrackMapService::anon_struct_1


IRacingTools.Shared.Services.TrackMapService +-- IRacingTools.Shared.Services.TrackMapService::anon_struct_2


IRacingTools.Shared.VR.VRRenderConfig +-- IRacingTools.Shared.VR.VRRenderConfig::Quirks


IRacingTools.Shared.VR.VRRenderConfig::Quirks +-- IRacingTools.Shared.VR.VRRenderConfig::Quirks::Upscaling


IRacingTools.Shared.UI.Window +-- IRacingTools.Shared.UI.Window::CreateOptions


IRacingTools.Shared.Graphics.WriteReadBuffer +-- IRacingTools.Shared.Graphics.WriteReadBuffer::Config


IRacingTools.Shared.SHM.Writer +-- IRacingTools.Shared.SHM.Writer::NextFrameInfo




@enduml
