name: App Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


#permissions:
#  contents: read

jobs:
  build:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [  windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows-static
            vcpkgCommitId: '47bf3d1ac192b3fa0feb6e6ac9c845de179eebe9'
    env:
      # Path to the solution file relative to the root of the project.
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      # Configuration type to build.
      # You can convert this to a build matrix if you need coverage of multiple configuration types.
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_PLATFORM: x64
      BUILD_CONFIGURATION: Debug

    steps:
      - uses: actions/checkout@v3

      - name: get-cmake
        uses: lukka/get-cmake@v3.21.1

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Just install vcpkg for now, do not install any ports in this step yet.
          runVcpkgInstall: false

          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
          vcpkgJsonGlob: '**/vcpkg.json'

          #          vcpkgGitCommitId: '47bf3d1ac192b3fa0feb6e6ac9c845de179eebe9'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.

          # appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          # Ensure the vcpkg artifacts are cached, they are generated in the 'CMAKE_BINARY_DIR/vcpkg_installed'.
          #          additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed

      - name: 'Run CMake with Ninja, install dependencies with vcpkg, build with CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja'
          buildPreset: 'ninja-release-preset'
          # buildDirectory: ${{ env.buildDir }}
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
#          configurePresetAdditionalArgs:
#            - '-GNinja'
#            - '-DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake'
#            - '-DKANGARU_TEST=ON'
#            - '-DSPDLOG_WCHAR_SUPPORT=1'
#            - '-DSPDLOG_WCHAR_TO_UTF8_SUPPORT=1'
#            - '-DVCPKG_ROOT=${{ runner.workspace }}/vcpkg'
#            - '-DVCPKG_DEFAULT_TRIPLET=${{ matrix.triplet }}'
#            - '-DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}'
#            - '-DVCPKG_CRT_LINKAGE=static'
#            - '-DVCPKG_LIBRARY_LINKAGE=static'
#            - '-DVCPKG_INSTALL_OPTIONS="--allow-unsupported"'


