name: Release

on:
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: bash

    name: "vrkit-release"
    environment: build
    runs-on: [ "windows-latest" ]
    concurrency:
      cancel-in-progress: false
      group: "vrkit-app-release"

    env: {}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "develop"
          fetch-depth: 1
          fetch-tags: true

      - name: Use Node v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          cd ${{github.workspace}}/scripts
          yarn install

      - name: 'Release'
        shell: bash
        run: |
          cd ${{github.workspace}}/scripts
          ./node_modules/.bin/cross-env GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} node release-version.mjs